//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.distinction;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.DateCtype;
import pt.cienciavitae.ns.common.InstitutionsCtype;
import pt.cienciavitae.ns.common.Iso3166CountryCtype;
import pt.cienciavitae.ns.common.KeywordsCtype;
import pt.cienciavitae.ns.common.RecordCtype;
import pt.cienciavitae.ns.common.ResearchClassificationsCtype;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.cienciavitae.pt/ns/common}record-ctype"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="distinction-type" type="{http://www.cienciavitae.pt/ns/distinction}distinction-type-ctype"/&gt;
 *         &lt;element name="distinction-name" type="{http://www.cienciavitae.pt/ns/common}string-255-stype"/&gt;
 *         &lt;element name="effective-date" type="{http://www.cienciavitae.pt/ns/common}year-stype" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cienciavitae.pt/ns/common}institutions" minOccurs="0"/&gt;
 *         &lt;element name="country" type="{http://www.cienciavitae.pt/ns/common}iso-3166-country-ctype" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.cienciavitae.pt/ns/common}string-255-stype" minOccurs="0"/&gt;
 *         &lt;element name="end-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.cienciavitae.pt/ns/common}research-classifications-keywords-group"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "distinctionType",
    "distinctionName",
    "effectiveDate",
    "institutions",
    "country",
    "description",
    "endDate",
    "researchClassifications",
    "keywords"
})
@XmlRootElement(name = "distinction")
public class Distinction
    extends RecordCtype
{

    @XmlElement(name = "distinction-type", required = true)
    protected DistinctionTypeCtype distinctionType;
    @XmlElement(name = "distinction-name", required = true)
    protected String distinctionName;
    @XmlElement(name = "effective-date")
    protected String effectiveDate;
    @XmlElement(namespace = "http://www.cienciavitae.pt/ns/common")
    protected InstitutionsCtype institutions;
    protected Iso3166CountryCtype country;
    protected String description;
    @XmlElement(name = "end-date")
    protected DateCtype endDate;
    @XmlElement(name = "research-classifications", namespace = "http://www.cienciavitae.pt/ns/common")
    protected ResearchClassificationsCtype researchClassifications;
    @XmlElement(namespace = "http://www.cienciavitae.pt/ns/common")
    protected KeywordsCtype keywords;

    /**
     * Gets the value of the distinctionType property.
     * 
     * @return
     *     possible object is
     *     {@link DistinctionTypeCtype }
     *     
     */
    public DistinctionTypeCtype getDistinctionType() {
        return distinctionType;
    }

    /**
     * Sets the value of the distinctionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistinctionTypeCtype }
     *     
     */
    public void setDistinctionType(DistinctionTypeCtype value) {
        this.distinctionType = value;
    }

    /**
     * Gets the value of the distinctionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistinctionName() {
        return distinctionName;
    }

    /**
     * Sets the value of the distinctionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistinctionName(String value) {
        this.distinctionName = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEffectiveDate(String value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the institutions property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionsCtype }
     *     
     */
    public InstitutionsCtype getInstitutions() {
        return institutions;
    }

    /**
     * Sets the value of the institutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionsCtype }
     *     
     */
    public void setInstitutions(InstitutionsCtype value) {
        this.institutions = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Iso3166CountryCtype }
     *     
     */
    public Iso3166CountryCtype getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Iso3166CountryCtype }
     *     
     */
    public void setCountry(Iso3166CountryCtype value) {
        this.country = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setEndDate(DateCtype value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the researchClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public ResearchClassificationsCtype getResearchClassifications() {
        return researchClassifications;
    }

    /**
     * Sets the value of the researchClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public void setResearchClassifications(ResearchClassificationsCtype value) {
        this.researchClassifications = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordsCtype }
     *     
     */
    public KeywordsCtype getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordsCtype }
     *     
     */
    public void setKeywords(KeywordsCtype value) {
        this.keywords = value;
    }

}
