//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.person_info;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="full-name" type="{http://www.cienciavitae.pt/ns/common}string-80-stype"/&gt;
 *         &lt;element name="names" type="{http://www.cienciavitae.pt/ns/common}string-80-stype" minOccurs="0"/&gt;
 *         &lt;element name="surnames" type="{http://www.cienciavitae.pt/ns/common}string-80-stype" minOccurs="0"/&gt;
 *         &lt;element name="presented-name" type="{http://www.cienciavitae.pt/ns/common}string-80-stype"/&gt;
 *         &lt;element name="date-of-birth" type="{http://www.cienciavitae.pt/ns/person-info}date-of-birth-ctype"/&gt;
 *         &lt;element name="gender" type="{http://www.cienciavitae.pt/ns/person-info}gender-ctype"/&gt;
 *         &lt;element name="photography" type="{http://www.cienciavitae.pt/ns/person-info}photography-ctype"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fullName",
    "names",
    "surnames",
    "presentedName",
    "dateOfBirth",
    "gender",
    "photography"
})
@XmlRootElement(name = "person-info")
public class PersonInfo {

    @XmlElement(name = "full-name", required = true)
    protected String fullName;
    protected String names;
    protected String surnames;
    @XmlElement(name = "presented-name", required = true)
    protected String presentedName;
    @XmlElement(name = "date-of-birth", required = true)
    protected DateOfBirthCtype dateOfBirth;
    @XmlElement(required = true)
    protected GenderCtype gender;
    @XmlElement(required = true)
    protected PhotographyCtype photography;

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the names property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNames() {
        return names;
    }

    /**
     * Sets the value of the names property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNames(String value) {
        this.names = value;
    }

    /**
     * Gets the value of the surnames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurnames() {
        return surnames;
    }

    /**
     * Sets the value of the surnames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurnames(String value) {
        this.surnames = value;
    }

    /**
     * Gets the value of the presentedName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPresentedName() {
        return presentedName;
    }

    /**
     * Sets the value of the presentedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPresentedName(String value) {
        this.presentedName = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link DateOfBirthCtype }
     *     
     */
    public DateOfBirthCtype getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateOfBirthCtype }
     *     
     */
    public void setDateOfBirth(DateOfBirthCtype value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link GenderCtype }
     *     
     */
    public GenderCtype getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderCtype }
     *     
     */
    public void setGender(GenderCtype value) {
        this.gender = value;
    }

    /**
     * Gets the value of the photography property.
     * 
     * @return
     *     possible object is
     *     {@link PhotographyCtype }
     *     
     */
    public PhotographyCtype getPhotography() {
        return photography;
    }

    /**
     * Sets the value of the photography property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhotographyCtype }
     *     
     */
    public void setPhotography(PhotographyCtype value) {
        this.photography = value;
    }

}
