//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.DateCtype;
import pt.cienciavitae.ns.common.KeywordsCtype;
import pt.cienciavitae.ns.common.ResearchClassificationsCtype;


/**
 * Corresponding to "output:output-type[@code='P106']"
 * 
 * <p>Java class for book-review-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="book-review-ctype"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="review-title" type="{http://www.cienciavitae.pt/ns/common}string-400-stype"/&gt;
 *         &lt;element name="published-in" type="{http://www.cienciavitae.pt/ns/common}string-400-stype" minOccurs="0"/&gt;
 *         &lt;element name="review-volume" type="{http://www.cienciavitae.pt/ns/common}string-10-stype" minOccurs="0"/&gt;
 *         &lt;element name="review-issue" type="{http://www.cienciavitae.pt/ns/common}string-10-stype" minOccurs="0"/&gt;
 *         &lt;element name="page-range-from" type="{http://www.cienciavitae.pt/ns/common}string-20-stype" minOccurs="0"/&gt;
 *         &lt;element name="page-range-to" type="{http://www.cienciavitae.pt/ns/common}string-20-stype" minOccurs="0"/&gt;
 *         &lt;element name="refereed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="publication-status" type="{http://www.cienciavitae.pt/ns/output}publication-status-ctype" minOccurs="0"/&gt;
 *         &lt;element name="review-publication" type="{http://www.cienciavitae.pt/ns/output}review-publication-ctype" minOccurs="0"/&gt;
 *         &lt;element name="date-of-review-publication" type="{http://www.cienciavitae.pt/ns/common}date-ctype"/&gt;
 *         &lt;element name="review-publisher" type="{http://www.cienciavitae.pt/ns/common}string-255-stype" minOccurs="0"/&gt;
 *         &lt;element name="url" type="{http://www.cienciavitae.pt/ns/common}string-uri-stype" minOccurs="0"/&gt;
 *         &lt;element name="book-title" type="{http://www.cienciavitae.pt/ns/common}string-400-stype" minOccurs="0"/&gt;
 *         &lt;element name="book-volume" type="{http://www.cienciavitae.pt/ns/common}string-10-stype" minOccurs="0"/&gt;
 *         &lt;element name="book-edition" type="{http://www.cienciavitae.pt/ns/common}string-10-stype" minOccurs="0"/&gt;
 *         &lt;element name="book-refereed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="book-publication-year" type="{http://www.cienciavitae.pt/ns/common}year-stype" minOccurs="0"/&gt;
 *         &lt;element name="book-publication-location" type="{http://www.cienciavitae.pt/ns/output}publication-location-ctype" minOccurs="0"/&gt;
 *         &lt;element name="identifiers" type="{http://www.cienciavitae.pt/ns/output}identifiers-ctype" minOccurs="0"/&gt;
 *         &lt;element name="authors" type="{http://www.cienciavitae.pt/ns/output}authors-ctype"/&gt;
 *         &lt;group ref="{http://www.cienciavitae.pt/ns/common}research-classifications-keywords-group"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "book-review-ctype", propOrder = {
    "reviewTitle",
    "publishedIn",
    "reviewVolume",
    "reviewIssue",
    "pageRangeFrom",
    "pageRangeTo",
    "refereed",
    "publicationStatus",
    "reviewPublication",
    "dateOfReviewPublication",
    "reviewPublisher",
    "url",
    "bookTitle",
    "bookVolume",
    "bookEdition",
    "bookRefereed",
    "bookPublicationYear",
    "bookPublicationLocation",
    "identifiers",
    "authors",
    "researchClassifications",
    "keywords"
})
public class BookReviewCtype {

    @XmlElement(name = "review-title", required = true)
    protected String reviewTitle;
    @XmlElement(name = "published-in")
    protected String publishedIn;
    @XmlElement(name = "review-volume")
    protected String reviewVolume;
    @XmlElement(name = "review-issue")
    protected String reviewIssue;
    @XmlElement(name = "page-range-from")
    protected String pageRangeFrom;
    @XmlElement(name = "page-range-to")
    protected String pageRangeTo;
    protected Boolean refereed;
    @XmlElement(name = "publication-status")
    protected PublicationStatusCtype publicationStatus;
    @XmlElement(name = "review-publication")
    protected ReviewPublicationCtype reviewPublication;
    @XmlElement(name = "date-of-review-publication", required = true)
    protected DateCtype dateOfReviewPublication;
    @XmlElement(name = "review-publisher")
    protected String reviewPublisher;
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlElement(name = "book-title")
    protected String bookTitle;
    @XmlElement(name = "book-volume")
    protected String bookVolume;
    @XmlElement(name = "book-edition")
    protected String bookEdition;
    @XmlElement(name = "book-refereed")
    protected Boolean bookRefereed;
    @XmlElement(name = "book-publication-year")
    protected String bookPublicationYear;
    @XmlElement(name = "book-publication-location")
    protected PublicationLocationCtype bookPublicationLocation;
    protected IdentifiersCtype identifiers;
    @XmlElement(required = true)
    protected AuthorsCtype authors;
    @XmlElement(name = "research-classifications", namespace = "http://www.cienciavitae.pt/ns/common")
    protected ResearchClassificationsCtype researchClassifications;
    @XmlElement(namespace = "http://www.cienciavitae.pt/ns/common")
    protected KeywordsCtype keywords;

    /**
     * Gets the value of the reviewTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewTitle() {
        return reviewTitle;
    }

    /**
     * Sets the value of the reviewTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewTitle(String value) {
        this.reviewTitle = value;
    }

    /**
     * Gets the value of the publishedIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublishedIn() {
        return publishedIn;
    }

    /**
     * Sets the value of the publishedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublishedIn(String value) {
        this.publishedIn = value;
    }

    /**
     * Gets the value of the reviewVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewVolume() {
        return reviewVolume;
    }

    /**
     * Sets the value of the reviewVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewVolume(String value) {
        this.reviewVolume = value;
    }

    /**
     * Gets the value of the reviewIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewIssue() {
        return reviewIssue;
    }

    /**
     * Sets the value of the reviewIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewIssue(String value) {
        this.reviewIssue = value;
    }

    /**
     * Gets the value of the pageRangeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageRangeFrom() {
        return pageRangeFrom;
    }

    /**
     * Sets the value of the pageRangeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageRangeFrom(String value) {
        this.pageRangeFrom = value;
    }

    /**
     * Gets the value of the pageRangeTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageRangeTo() {
        return pageRangeTo;
    }

    /**
     * Sets the value of the pageRangeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageRangeTo(String value) {
        this.pageRangeTo = value;
    }

    /**
     * Gets the value of the refereed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRefereed() {
        return refereed;
    }

    /**
     * Sets the value of the refereed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRefereed(Boolean value) {
        this.refereed = value;
    }

    /**
     * Gets the value of the publicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationStatusCtype }
     *     
     */
    public PublicationStatusCtype getPublicationStatus() {
        return publicationStatus;
    }

    /**
     * Sets the value of the publicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationStatusCtype }
     *     
     */
    public void setPublicationStatus(PublicationStatusCtype value) {
        this.publicationStatus = value;
    }

    /**
     * Gets the value of the reviewPublication property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewPublicationCtype }
     *     
     */
    public ReviewPublicationCtype getReviewPublication() {
        return reviewPublication;
    }

    /**
     * Sets the value of the reviewPublication property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewPublicationCtype }
     *     
     */
    public void setReviewPublication(ReviewPublicationCtype value) {
        this.reviewPublication = value;
    }

    /**
     * Gets the value of the dateOfReviewPublication property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getDateOfReviewPublication() {
        return dateOfReviewPublication;
    }

    /**
     * Sets the value of the dateOfReviewPublication property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setDateOfReviewPublication(DateCtype value) {
        this.dateOfReviewPublication = value;
    }

    /**
     * Gets the value of the reviewPublisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewPublisher() {
        return reviewPublisher;
    }

    /**
     * Sets the value of the reviewPublisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewPublisher(String value) {
        this.reviewPublisher = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the bookTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookTitle() {
        return bookTitle;
    }

    /**
     * Sets the value of the bookTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookTitle(String value) {
        this.bookTitle = value;
    }

    /**
     * Gets the value of the bookVolume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookVolume() {
        return bookVolume;
    }

    /**
     * Sets the value of the bookVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookVolume(String value) {
        this.bookVolume = value;
    }

    /**
     * Gets the value of the bookEdition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookEdition() {
        return bookEdition;
    }

    /**
     * Sets the value of the bookEdition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookEdition(String value) {
        this.bookEdition = value;
    }

    /**
     * Gets the value of the bookRefereed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBookRefereed() {
        return bookRefereed;
    }

    /**
     * Sets the value of the bookRefereed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBookRefereed(Boolean value) {
        this.bookRefereed = value;
    }

    /**
     * Gets the value of the bookPublicationYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookPublicationYear() {
        return bookPublicationYear;
    }

    /**
     * Sets the value of the bookPublicationYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookPublicationYear(String value) {
        this.bookPublicationYear = value;
    }

    /**
     * Gets the value of the bookPublicationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationLocationCtype }
     *     
     */
    public PublicationLocationCtype getBookPublicationLocation() {
        return bookPublicationLocation;
    }

    /**
     * Sets the value of the bookPublicationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationLocationCtype }
     *     
     */
    public void setBookPublicationLocation(PublicationLocationCtype value) {
        this.bookPublicationLocation = value;
    }

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiersCtype }
     *     
     */
    public IdentifiersCtype getIdentifiers() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiersCtype }
     *     
     */
    public void setIdentifiers(IdentifiersCtype value) {
        this.identifiers = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorsCtype }
     *     
     */
    public AuthorsCtype getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorsCtype }
     *     
     */
    public void setAuthors(AuthorsCtype value) {
        this.authors = value;
    }

    /**
     * Gets the value of the researchClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public ResearchClassificationsCtype getResearchClassifications() {
        return researchClassifications;
    }

    /**
     * Sets the value of the researchClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public void setResearchClassifications(ResearchClassificationsCtype value) {
        this.researchClassifications = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordsCtype }
     *     
     */
    public KeywordsCtype getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordsCtype }
     *     
     */
    public void setKeywords(KeywordsCtype value) {
        this.keywords = value;
    }

}
