//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.DateCtype;
import pt.cienciavitae.ns.common.KeywordsCtype;
import pt.cienciavitae.ns.common.ResearchClassificationsCtype;


/**
 * Corresponding to "output:output-type[@code='P122']"
 * 
 * <p>Java class for conference-paper-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="conference-paper-ctype"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="paper-title" type="{http://www.cienciavitae.pt/ns/common}string-400-stype"/&gt;
 *         &lt;element name="conference-name" type="{http://www.cienciavitae.pt/ns/common}string-400-stype" minOccurs="0"/&gt;
 *         &lt;element name="presentation-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *         &lt;element name="conference-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype"/&gt;
 *         &lt;element name="conference-location" type="{http://www.cienciavitae.pt/ns/output}publication-location-ctype" minOccurs="0"/&gt;
 *         &lt;element name="proceedings-title" type="{http://www.cienciavitae.pt/ns/common}string-400-stype" minOccurs="0"/&gt;
 *         &lt;element name="page-range-from" type="{http://www.cienciavitae.pt/ns/common}string-20-stype" minOccurs="0"/&gt;
 *         &lt;element name="page-range-to" type="{http://www.cienciavitae.pt/ns/common}string-20-stype" minOccurs="0"/&gt;
 *         &lt;element name="publication-status" type="{http://www.cienciavitae.pt/ns/output}publication-status-ctype" minOccurs="0"/&gt;
 *         &lt;element name="publication-location" type="{http://www.cienciavitae.pt/ns/output}publication-location-ctype" minOccurs="0"/&gt;
 *         &lt;element name="proceedings-publisher" type="{http://www.cienciavitae.pt/ns/common}string-255-stype" minOccurs="0"/&gt;
 *         &lt;element name="authoring-role" type="{http://www.cienciavitae.pt/ns/output}publication-role-ctype" minOccurs="0"/&gt;
 *         &lt;element name="identifiers" type="{http://www.cienciavitae.pt/ns/output}identifiers-ctype" minOccurs="0"/&gt;
 *         &lt;element name="authors" type="{http://www.cienciavitae.pt/ns/output}authors-ctype"/&gt;
 *         &lt;element name="presenters" type="{http://www.cienciavitae.pt/ns/output}authors-ctype" minOccurs="0"/&gt;
 *         &lt;element name="proceedings-editors" type="{http://www.cienciavitae.pt/ns/output}authors-ctype" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.cienciavitae.pt/ns/common}research-classifications-keywords-group"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conference-paper-ctype", propOrder = {
    "paperTitle",
    "conferenceName",
    "presentationDate",
    "conferenceDate",
    "conferenceLocation",
    "proceedingsTitle",
    "pageRangeFrom",
    "pageRangeTo",
    "publicationStatus",
    "publicationLocation",
    "proceedingsPublisher",
    "authoringRole",
    "identifiers",
    "authors",
    "presenters",
    "proceedingsEditors",
    "researchClassifications",
    "keywords"
})
public class ConferencePaperCtype {

    @XmlElement(name = "paper-title", required = true)
    protected String paperTitle;
    @XmlElement(name = "conference-name")
    protected String conferenceName;
    @XmlElement(name = "presentation-date")
    protected DateCtype presentationDate;
    @XmlElement(name = "conference-date", required = true)
    protected DateCtype conferenceDate;
    @XmlElement(name = "conference-location")
    protected PublicationLocationCtype conferenceLocation;
    @XmlElement(name = "proceedings-title")
    protected String proceedingsTitle;
    @XmlElement(name = "page-range-from")
    protected String pageRangeFrom;
    @XmlElement(name = "page-range-to")
    protected String pageRangeTo;
    @XmlElement(name = "publication-status")
    protected PublicationStatusCtype publicationStatus;
    @XmlElement(name = "publication-location")
    protected PublicationLocationCtype publicationLocation;
    @XmlElement(name = "proceedings-publisher")
    protected String proceedingsPublisher;
    @XmlElement(name = "authoring-role")
    protected PublicationRoleCtype authoringRole;
    protected IdentifiersCtype identifiers;
    @XmlElement(required = true)
    protected AuthorsCtype authors;
    protected AuthorsCtype presenters;
    @XmlElement(name = "proceedings-editors")
    protected AuthorsCtype proceedingsEditors;
    @XmlElement(name = "research-classifications", namespace = "http://www.cienciavitae.pt/ns/common")
    protected ResearchClassificationsCtype researchClassifications;
    @XmlElement(namespace = "http://www.cienciavitae.pt/ns/common")
    protected KeywordsCtype keywords;

    /**
     * Gets the value of the paperTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperTitle() {
        return paperTitle;
    }

    /**
     * Sets the value of the paperTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperTitle(String value) {
        this.paperTitle = value;
    }

    /**
     * Gets the value of the conferenceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConferenceName() {
        return conferenceName;
    }

    /**
     * Sets the value of the conferenceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConferenceName(String value) {
        this.conferenceName = value;
    }

    /**
     * Gets the value of the presentationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getPresentationDate() {
        return presentationDate;
    }

    /**
     * Sets the value of the presentationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setPresentationDate(DateCtype value) {
        this.presentationDate = value;
    }

    /**
     * Gets the value of the conferenceDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getConferenceDate() {
        return conferenceDate;
    }

    /**
     * Sets the value of the conferenceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setConferenceDate(DateCtype value) {
        this.conferenceDate = value;
    }

    /**
     * Gets the value of the conferenceLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationLocationCtype }
     *     
     */
    public PublicationLocationCtype getConferenceLocation() {
        return conferenceLocation;
    }

    /**
     * Sets the value of the conferenceLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationLocationCtype }
     *     
     */
    public void setConferenceLocation(PublicationLocationCtype value) {
        this.conferenceLocation = value;
    }

    /**
     * Gets the value of the proceedingsTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProceedingsTitle() {
        return proceedingsTitle;
    }

    /**
     * Sets the value of the proceedingsTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProceedingsTitle(String value) {
        this.proceedingsTitle = value;
    }

    /**
     * Gets the value of the pageRangeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageRangeFrom() {
        return pageRangeFrom;
    }

    /**
     * Sets the value of the pageRangeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageRangeFrom(String value) {
        this.pageRangeFrom = value;
    }

    /**
     * Gets the value of the pageRangeTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageRangeTo() {
        return pageRangeTo;
    }

    /**
     * Sets the value of the pageRangeTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageRangeTo(String value) {
        this.pageRangeTo = value;
    }

    /**
     * Gets the value of the publicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationStatusCtype }
     *     
     */
    public PublicationStatusCtype getPublicationStatus() {
        return publicationStatus;
    }

    /**
     * Sets the value of the publicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationStatusCtype }
     *     
     */
    public void setPublicationStatus(PublicationStatusCtype value) {
        this.publicationStatus = value;
    }

    /**
     * Gets the value of the publicationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationLocationCtype }
     *     
     */
    public PublicationLocationCtype getPublicationLocation() {
        return publicationLocation;
    }

    /**
     * Sets the value of the publicationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationLocationCtype }
     *     
     */
    public void setPublicationLocation(PublicationLocationCtype value) {
        this.publicationLocation = value;
    }

    /**
     * Gets the value of the proceedingsPublisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProceedingsPublisher() {
        return proceedingsPublisher;
    }

    /**
     * Sets the value of the proceedingsPublisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProceedingsPublisher(String value) {
        this.proceedingsPublisher = value;
    }

    /**
     * Gets the value of the authoringRole property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationRoleCtype }
     *     
     */
    public PublicationRoleCtype getAuthoringRole() {
        return authoringRole;
    }

    /**
     * Sets the value of the authoringRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationRoleCtype }
     *     
     */
    public void setAuthoringRole(PublicationRoleCtype value) {
        this.authoringRole = value;
    }

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiersCtype }
     *     
     */
    public IdentifiersCtype getIdentifiers() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiersCtype }
     *     
     */
    public void setIdentifiers(IdentifiersCtype value) {
        this.identifiers = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorsCtype }
     *     
     */
    public AuthorsCtype getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorsCtype }
     *     
     */
    public void setAuthors(AuthorsCtype value) {
        this.authors = value;
    }

    /**
     * Gets the value of the presenters property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorsCtype }
     *     
     */
    public AuthorsCtype getPresenters() {
        return presenters;
    }

    /**
     * Sets the value of the presenters property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorsCtype }
     *     
     */
    public void setPresenters(AuthorsCtype value) {
        this.presenters = value;
    }

    /**
     * Gets the value of the proceedingsEditors property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorsCtype }
     *     
     */
    public AuthorsCtype getProceedingsEditors() {
        return proceedingsEditors;
    }

    /**
     * Sets the value of the proceedingsEditors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorsCtype }
     *     
     */
    public void setProceedingsEditors(AuthorsCtype value) {
        this.proceedingsEditors = value;
    }

    /**
     * Gets the value of the researchClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public ResearchClassificationsCtype getResearchClassifications() {
        return researchClassifications;
    }

    /**
     * Sets the value of the researchClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public void setResearchClassifications(ResearchClassificationsCtype value) {
        this.researchClassifications = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordsCtype }
     *     
     */
    public KeywordsCtype getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordsCtype }
     *     
     */
    public void setKeywords(KeywordsCtype value) {
        this.keywords = value;
    }

}
