//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.IdentifierRelationshipTypeCtype;


/**
 * <p>Java class for identifier-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identifier-ctype"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="identifier" type="{http://www.cienciavitae.pt/ns/common}string-255-stype"/&gt;
 *         &lt;element name="identifier-type" type="{http://www.cienciavitae.pt/ns/output}identifier-type-ctype"/&gt;
 *         &lt;element name="relationship-type" type="{http://www.cienciavitae.pt/ns/common}identifier-relationship-type-ctype"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identifier-ctype", propOrder = {
    "identifier",
    "identifierType",
    "relationshipType"
})
public class IdentifierCtype {

    @XmlElement(required = true)
    protected String identifier;
    @XmlElement(name = "identifier-type", required = true)
    protected IdentifierTypeCtype identifierType;
    @XmlElement(name = "relationship-type", required = true)
    protected IdentifierRelationshipTypeCtype relationshipType;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the identifierType property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierTypeCtype }
     *     
     */
    public IdentifierTypeCtype getIdentifierType() {
        return identifierType;
    }

    /**
     * Sets the value of the identifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierTypeCtype }
     *     
     */
    public void setIdentifierType(IdentifierTypeCtype value) {
        this.identifierType = value;
    }

    /**
     * Gets the value of the relationshipType property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierRelationshipTypeCtype }
     *     
     */
    public IdentifierRelationshipTypeCtype getRelationshipType() {
        return relationshipType;
    }

    /**
     * Sets the value of the relationshipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierRelationshipTypeCtype }
     *     
     */
    public void setRelationshipType(IdentifierRelationshipTypeCtype value) {
        this.relationshipType = value;
    }

}
