//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.DateCtype;
import pt.cienciavitae.ns.common.KeywordsCtype;
import pt.cienciavitae.ns.common.ResearchClassificationsCtype;


/**
 * Corresponding to "output:output-type[@code='P102']"
 * 
 * <p>Java class for journal-issue-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="journal-issue-ctype"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="issue-title" type="{http://www.cienciavitae.pt/ns/common}string-400-stype"/&gt;
 *         &lt;element name="journal" type="{http://www.cienciavitae.pt/ns/common}string-400-stype" minOccurs="0"/&gt;
 *         &lt;element name="volume" type="{http://www.cienciavitae.pt/ns/common}string-10-stype" minOccurs="0"/&gt;
 *         &lt;element name="issue-number" type="{http://www.cienciavitae.pt/ns/common}string-10-stype" minOccurs="0"/&gt;
 *         &lt;element name="number-of-pages" type="{http://www.cienciavitae.pt/ns/common}int-6-stype" minOccurs="0"/&gt;
 *         &lt;element name="refereed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="publication-status" type="{http://www.cienciavitae.pt/ns/output}publication-status-ctype" minOccurs="0"/&gt;
 *         &lt;element name="publication-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype"/&gt;
 *         &lt;element name="publication-location" type="{http://www.cienciavitae.pt/ns/output}publication-location-ctype" minOccurs="0"/&gt;
 *         &lt;element name="editing-role" type="{http://www.cienciavitae.pt/ns/output}publication-editor-role-ctype" minOccurs="0"/&gt;
 *         &lt;element name="url" type="{http://www.cienciavitae.pt/ns/common}string-uri-stype" minOccurs="0"/&gt;
 *         &lt;element name="identifiers" type="{http://www.cienciavitae.pt/ns/output}identifiers-ctype" minOccurs="0"/&gt;
 *         &lt;element name="editors" type="{http://www.cienciavitae.pt/ns/output}authors-ctype"/&gt;
 *         &lt;group ref="{http://www.cienciavitae.pt/ns/common}research-classifications-keywords-group"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "journal-issue-ctype", propOrder = {
    "issueTitle",
    "journal",
    "volume",
    "issueNumber",
    "numberOfPages",
    "refereed",
    "publicationStatus",
    "publicationDate",
    "publicationLocation",
    "editingRole",
    "url",
    "identifiers",
    "editors",
    "researchClassifications",
    "keywords"
})
public class JournalIssueCtype {

    @XmlElement(name = "issue-title", required = true)
    protected String issueTitle;
    protected String journal;
    protected String volume;
    @XmlElement(name = "issue-number")
    protected String issueNumber;
    @XmlElement(name = "number-of-pages")
    protected Integer numberOfPages;
    protected Boolean refereed;
    @XmlElement(name = "publication-status")
    protected PublicationStatusCtype publicationStatus;
    @XmlElement(name = "publication-date", required = true)
    protected DateCtype publicationDate;
    @XmlElement(name = "publication-location")
    protected PublicationLocationCtype publicationLocation;
    @XmlElement(name = "editing-role")
    protected PublicationEditorRoleCtype editingRole;
    @XmlSchemaType(name = "anyURI")
    protected String url;
    protected IdentifiersCtype identifiers;
    @XmlElement(required = true)
    protected AuthorsCtype editors;
    @XmlElement(name = "research-classifications", namespace = "http://www.cienciavitae.pt/ns/common")
    protected ResearchClassificationsCtype researchClassifications;
    @XmlElement(namespace = "http://www.cienciavitae.pt/ns/common")
    protected KeywordsCtype keywords;

    /**
     * Gets the value of the issueTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueTitle() {
        return issueTitle;
    }

    /**
     * Sets the value of the issueTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueTitle(String value) {
        this.issueTitle = value;
    }

    /**
     * Gets the value of the journal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJournal() {
        return journal;
    }

    /**
     * Sets the value of the journal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJournal(String value) {
        this.journal = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolume(String value) {
        this.volume = value;
    }

    /**
     * Gets the value of the issueNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueNumber() {
        return issueNumber;
    }

    /**
     * Sets the value of the issueNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueNumber(String value) {
        this.issueNumber = value;
    }

    /**
     * Gets the value of the numberOfPages property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfPages() {
        return numberOfPages;
    }

    /**
     * Sets the value of the numberOfPages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfPages(Integer value) {
        this.numberOfPages = value;
    }

    /**
     * Gets the value of the refereed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRefereed() {
        return refereed;
    }

    /**
     * Sets the value of the refereed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRefereed(Boolean value) {
        this.refereed = value;
    }

    /**
     * Gets the value of the publicationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationStatusCtype }
     *     
     */
    public PublicationStatusCtype getPublicationStatus() {
        return publicationStatus;
    }

    /**
     * Sets the value of the publicationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationStatusCtype }
     *     
     */
    public void setPublicationStatus(PublicationStatusCtype value) {
        this.publicationStatus = value;
    }

    /**
     * Gets the value of the publicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getPublicationDate() {
        return publicationDate;
    }

    /**
     * Sets the value of the publicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setPublicationDate(DateCtype value) {
        this.publicationDate = value;
    }

    /**
     * Gets the value of the publicationLocation property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationLocationCtype }
     *     
     */
    public PublicationLocationCtype getPublicationLocation() {
        return publicationLocation;
    }

    /**
     * Sets the value of the publicationLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationLocationCtype }
     *     
     */
    public void setPublicationLocation(PublicationLocationCtype value) {
        this.publicationLocation = value;
    }

    /**
     * Gets the value of the editingRole property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationEditorRoleCtype }
     *     
     */
    public PublicationEditorRoleCtype getEditingRole() {
        return editingRole;
    }

    /**
     * Sets the value of the editingRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationEditorRoleCtype }
     *     
     */
    public void setEditingRole(PublicationEditorRoleCtype value) {
        this.editingRole = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the identifiers property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifiersCtype }
     *     
     */
    public IdentifiersCtype getIdentifiers() {
        return identifiers;
    }

    /**
     * Sets the value of the identifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifiersCtype }
     *     
     */
    public void setIdentifiers(IdentifiersCtype value) {
        this.identifiers = value;
    }

    /**
     * Gets the value of the editors property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorsCtype }
     *     
     */
    public AuthorsCtype getEditors() {
        return editors;
    }

    /**
     * Sets the value of the editors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorsCtype }
     *     
     */
    public void setEditors(AuthorsCtype value) {
        this.editors = value;
    }

    /**
     * Gets the value of the researchClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public ResearchClassificationsCtype getResearchClassifications() {
        return researchClassifications;
    }

    /**
     * Sets the value of the researchClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public void setResearchClassifications(ResearchClassificationsCtype value) {
        this.researchClassifications = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordsCtype }
     *     
     */
    public KeywordsCtype getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordsCtype }
     *     
     */
    public void setKeywords(KeywordsCtype value) {
        this.keywords = value;
    }

}
