//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.output;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.ExtendedRecordCtype;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.cienciavitae.pt/ns/common}extended-record-ctype"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="output-category" type="{http://www.cienciavitae.pt/ns/output}output-category-ctype" minOccurs="0"/&gt;
 *         &lt;element name="output-type" type="{http://www.cienciavitae.pt/ns/output}output-type-ctype"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="journal-article" type="{http://www.cienciavitae.pt/ns/output}journal-article-ctype"/&gt;
 *           &lt;element name="journal-issue" type="{http://www.cienciavitae.pt/ns/output}journal-issue-ctype"/&gt;
 *           &lt;element name="book" type="{http://www.cienciavitae.pt/ns/output}book-ctype"/&gt;
 *           &lt;element name="edited-book" type="{http://www.cienciavitae.pt/ns/output}edited-book-ctype"/&gt;
 *           &lt;element name="book-chapter" type="{http://www.cienciavitae.pt/ns/output}book-chapter-ctype"/&gt;
 *           &lt;element name="book-review" type="{http://www.cienciavitae.pt/ns/output}book-review-ctype"/&gt;
 *           &lt;element name="translation" type="{http://www.cienciavitae.pt/ns/output}translation-ctype"/&gt;
 *           &lt;element name="dissertation" type="{http://www.cienciavitae.pt/ns/output}dissertation-ctype"/&gt;
 *           &lt;element name="newspapper-article" type="{http://www.cienciavitae.pt/ns/output}newspapper-article-ctype"/&gt;
 *           &lt;element name="newsletter-article" type="{http://www.cienciavitae.pt/ns/output}newsletter-article-ctype"/&gt;
 *           &lt;element name="encyclopedia-entry" type="{http://www.cienciavitae.pt/ns/output}encyclopedia-entry-ctype"/&gt;
 *           &lt;element name="magazine-article" type="{http://www.cienciavitae.pt/ns/output}magazine-article-ctype"/&gt;
 *           &lt;element name="dictionary-entry" type="{http://www.cienciavitae.pt/ns/output}dictionary-entry-ctype"/&gt;
 *           &lt;element name="report" type="{http://www.cienciavitae.pt/ns/output}report-ctype"/&gt;
 *           &lt;element name="working-paper" type="{http://www.cienciavitae.pt/ns/output}working-paper-ctype"/&gt;
 *           &lt;element name="manual" type="{http://www.cienciavitae.pt/ns/output}manual-ctype"/&gt;
 *           &lt;element name="online-resource" type="{http://www.cienciavitae.pt/ns/output}online-resource-ctype"/&gt;
 *           &lt;element name="test" type="{http://www.cienciavitae.pt/ns/output}test-ctype"/&gt;
 *           &lt;element name="website" type="{http://www.cienciavitae.pt/ns/output}website-ctype"/&gt;
 *           &lt;element name="conference-paper" type="{http://www.cienciavitae.pt/ns/output}conference-paper-ctype"/&gt;
 *           &lt;element name="conference-abstract" type="{http://www.cienciavitae.pt/ns/output}conference-abstract-ctype"/&gt;
 *           &lt;element name="conference-poster" type="{http://www.cienciavitae.pt/ns/output}conference-poster-ctype"/&gt;
 *           &lt;element name="exhibition-catalogue" type="{http://www.cienciavitae.pt/ns/output}exhibition-catalogue-ctype"/&gt;
 *           &lt;element name="preface-postface" type="{http://www.cienciavitae.pt/ns/output}preface-postface-ctype"/&gt;
 *           &lt;element name="artistic-exhibition" type="{http://www.cienciavitae.pt/ns/output}artistic-exhibition-ctype"/&gt;
 *           &lt;element name="audio-recording" type="{http://www.cienciavitae.pt/ns/output}audio-recording-ctype"/&gt;
 *           &lt;element name="musical-composition" type="{http://www.cienciavitae.pt/ns/output}musical-composition-ctype"/&gt;
 *           &lt;element name="musical-performance" type="{http://www.cienciavitae.pt/ns/output}musical-performance-ctype"/&gt;
 *           &lt;element name="radio-tv-program" type="{http://www.cienciavitae.pt/ns/output}radio-tv-program-ctype"/&gt;
 *           &lt;element name="script" type="{http://www.cienciavitae.pt/ns/output}script-ctype"/&gt;
 *           &lt;element name="short-fiction" type="{http://www.cienciavitae.pt/ns/output}short-fiction-ctype"/&gt;
 *           &lt;element name="theatric" type="{http://www.cienciavitae.pt/ns/output}theatric-ctype"/&gt;
 *           &lt;element name="video-recording" type="{http://www.cienciavitae.pt/ns/output}video-recording-ctype"/&gt;
 *           &lt;element name="visual-artwork" type="{http://www.cienciavitae.pt/ns/output}visual-artwork-ctype"/&gt;
 *           &lt;element name="sound-design" type="{http://www.cienciavitae.pt/ns/output}sound-design-ctype"/&gt;
 *           &lt;element name="set-design" type="{http://www.cienciavitae.pt/ns/output}set-design-ctype"/&gt;
 *           &lt;element name="light-design" type="{http://www.cienciavitae.pt/ns/output}light-design-ctype"/&gt;
 *           &lt;element name="choreography" type="{http://www.cienciavitae.pt/ns/output}choreography-ctype"/&gt;
 *           &lt;element name="curatorial-museum-exhibition" type="{http://www.cienciavitae.pt/ns/output}curatorial-museum-exhibition-ctype"/&gt;
 *           &lt;element name="performance-art" type="{http://www.cienciavitae.pt/ns/output}performance-art-ctype"/&gt;
 *           &lt;element name="patent" type="{http://www.cienciavitae.pt/ns/output}patent-ctype"/&gt;
 *           &lt;element name="license" type="{http://www.cienciavitae.pt/ns/output}license-ctype"/&gt;
 *           &lt;element name="disclosure" type="{http://www.cienciavitae.pt/ns/output}disclosure-ctype"/&gt;
 *           &lt;element name="registered-copyright" type="{http://www.cienciavitae.pt/ns/output}registered-copyright-ctype"/&gt;
 *           &lt;element name="trademark" type="{http://www.cienciavitae.pt/ns/output}trademark-ctype"/&gt;
 *           &lt;element name="standard-or-policy" type="{http://www.cienciavitae.pt/ns/output}standard-or-policy-ctype"/&gt;
 *           &lt;element name="invention" type="{http://www.cienciavitae.pt/ns/output}invention-ctype"/&gt;
 *           &lt;element name="data-set" type="{http://www.cienciavitae.pt/ns/output}data-set-ctype"/&gt;
 *           &lt;element name="litigation" type="{http://www.cienciavitae.pt/ns/output}litigation-ctype"/&gt;
 *           &lt;element name="research-technique" type="{http://www.cienciavitae.pt/ns/output}research-technique-ctype"/&gt;
 *           &lt;element name="spin-off-company" type="{http://www.cienciavitae.pt/ns/output}spin-off-company-ctype"/&gt;
 *           &lt;element name="technical-standard" type="{http://www.cienciavitae.pt/ns/output}technical-standard-ctype"/&gt;
 *           &lt;element name="other-output" type="{http://www.cienciavitae.pt/ns/output}other-output-ctype"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outputCategory",
    "outputType",
    "journalArticle",
    "journalIssue",
    "book",
    "editedBook",
    "bookChapter",
    "bookReview",
    "translation",
    "dissertation",
    "newspapperArticle",
    "newsletterArticle",
    "encyclopediaEntry",
    "magazineArticle",
    "dictionaryEntry",
    "report",
    "workingPaper",
    "manual",
    "onlineResource",
    "test",
    "website",
    "conferencePaper",
    "conferenceAbstract",
    "conferencePoster",
    "exhibitionCatalogue",
    "prefacePostface",
    "artisticExhibition",
    "audioRecording",
    "musicalComposition",
    "musicalPerformance",
    "radioTvProgram",
    "script",
    "shortFiction",
    "theatric",
    "videoRecording",
    "visualArtwork",
    "soundDesign",
    "setDesign",
    "lightDesign",
    "choreography",
    "curatorialMuseumExhibition",
    "performanceArt",
    "patent",
    "license",
    "disclosure",
    "registeredCopyright",
    "trademark",
    "standardOrPolicy",
    "invention",
    "dataSet",
    "litigation",
    "researchTechnique",
    "spinOffCompany",
    "technicalStandard",
    "otherOutput"
})
@XmlRootElement(name = "output")
public class Output
    extends ExtendedRecordCtype
{

    @XmlElement(name = "output-category")
    protected OutputCategoryCtype outputCategory;
    @XmlElement(name = "output-type", required = true)
    protected OutputTypeCtype outputType;
    @XmlElement(name = "journal-article")
    protected JournalArticleCtype journalArticle;
    @XmlElement(name = "journal-issue")
    protected JournalIssueCtype journalIssue;
    protected BookCtype book;
    @XmlElement(name = "edited-book")
    protected EditedBookCtype editedBook;
    @XmlElement(name = "book-chapter")
    protected BookChapterCtype bookChapter;
    @XmlElement(name = "book-review")
    protected BookReviewCtype bookReview;
    protected TranslationCtype translation;
    protected DissertationCtype dissertation;
    @XmlElement(name = "newspapper-article")
    protected NewspapperArticleCtype newspapperArticle;
    @XmlElement(name = "newsletter-article")
    protected NewsletterArticleCtype newsletterArticle;
    @XmlElement(name = "encyclopedia-entry")
    protected EncyclopediaEntryCtype encyclopediaEntry;
    @XmlElement(name = "magazine-article")
    protected MagazineArticleCtype magazineArticle;
    @XmlElement(name = "dictionary-entry")
    protected DictionaryEntryCtype dictionaryEntry;
    protected ReportCtype report;
    @XmlElement(name = "working-paper")
    protected WorkingPaperCtype workingPaper;
    protected ManualCtype manual;
    @XmlElement(name = "online-resource")
    protected OnlineResourceCtype onlineResource;
    protected TestCtype test;
    protected WebsiteCtype website;
    @XmlElement(name = "conference-paper")
    protected ConferencePaperCtype conferencePaper;
    @XmlElement(name = "conference-abstract")
    protected ConferenceAbstractCtype conferenceAbstract;
    @XmlElement(name = "conference-poster")
    protected ConferencePosterCtype conferencePoster;
    @XmlElement(name = "exhibition-catalogue")
    protected ExhibitionCatalogueCtype exhibitionCatalogue;
    @XmlElement(name = "preface-postface")
    protected PrefacePostfaceCtype prefacePostface;
    @XmlElement(name = "artistic-exhibition")
    protected ArtisticExhibitionCtype artisticExhibition;
    @XmlElement(name = "audio-recording")
    protected AudioRecordingCtype audioRecording;
    @XmlElement(name = "musical-composition")
    protected MusicalCompositionCtype musicalComposition;
    @XmlElement(name = "musical-performance")
    protected MusicalPerformanceCtype musicalPerformance;
    @XmlElement(name = "radio-tv-program")
    protected RadioTvProgramCtype radioTvProgram;
    protected ScriptCtype script;
    @XmlElement(name = "short-fiction")
    protected ShortFictionCtype shortFiction;
    protected TheatricCtype theatric;
    @XmlElement(name = "video-recording")
    protected VideoRecordingCtype videoRecording;
    @XmlElement(name = "visual-artwork")
    protected VisualArtworkCtype visualArtwork;
    @XmlElement(name = "sound-design")
    protected SoundDesignCtype soundDesign;
    @XmlElement(name = "set-design")
    protected SetDesignCtype setDesign;
    @XmlElement(name = "light-design")
    protected LightDesignCtype lightDesign;
    protected ChoreographyCtype choreography;
    @XmlElement(name = "curatorial-museum-exhibition")
    protected CuratorialMuseumExhibitionCtype curatorialMuseumExhibition;
    @XmlElement(name = "performance-art")
    protected PerformanceArtCtype performanceArt;
    protected PatentCtype patent;
    protected LicenseCtype license;
    protected DisclosureCtype disclosure;
    @XmlElement(name = "registered-copyright")
    protected RegisteredCopyrightCtype registeredCopyright;
    protected TrademarkCtype trademark;
    @XmlElement(name = "standard-or-policy")
    protected StandardOrPolicyCtype standardOrPolicy;
    protected InventionCtype invention;
    @XmlElement(name = "data-set")
    protected DataSetCtype dataSet;
    protected LitigationCtype litigation;
    @XmlElement(name = "research-technique")
    protected ResearchTechniqueCtype researchTechnique;
    @XmlElement(name = "spin-off-company")
    protected SpinOffCompanyCtype spinOffCompany;
    @XmlElement(name = "technical-standard")
    protected TechnicalStandardCtype technicalStandard;
    @XmlElement(name = "other-output")
    protected OtherOutputCtype otherOutput;

    /**
     * Gets the value of the outputCategory property.
     * 
     * @return
     *     possible object is
     *     {@link OutputCategoryCtype }
     *     
     */
    public OutputCategoryCtype getOutputCategory() {
        return outputCategory;
    }

    /**
     * Sets the value of the outputCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputCategoryCtype }
     *     
     */
    public void setOutputCategory(OutputCategoryCtype value) {
        this.outputCategory = value;
    }

    /**
     * Gets the value of the outputType property.
     * 
     * @return
     *     possible object is
     *     {@link OutputTypeCtype }
     *     
     */
    public OutputTypeCtype getOutputType() {
        return outputType;
    }

    /**
     * Sets the value of the outputType property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputTypeCtype }
     *     
     */
    public void setOutputType(OutputTypeCtype value) {
        this.outputType = value;
    }

    /**
     * Gets the value of the journalArticle property.
     * 
     * @return
     *     possible object is
     *     {@link JournalArticleCtype }
     *     
     */
    public JournalArticleCtype getJournalArticle() {
        return journalArticle;
    }

    /**
     * Sets the value of the journalArticle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalArticleCtype }
     *     
     */
    public void setJournalArticle(JournalArticleCtype value) {
        this.journalArticle = value;
    }

    /**
     * Gets the value of the journalIssue property.
     * 
     * @return
     *     possible object is
     *     {@link JournalIssueCtype }
     *     
     */
    public JournalIssueCtype getJournalIssue() {
        return journalIssue;
    }

    /**
     * Sets the value of the journalIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link JournalIssueCtype }
     *     
     */
    public void setJournalIssue(JournalIssueCtype value) {
        this.journalIssue = value;
    }

    /**
     * Gets the value of the book property.
     * 
     * @return
     *     possible object is
     *     {@link BookCtype }
     *     
     */
    public BookCtype getBook() {
        return book;
    }

    /**
     * Sets the value of the book property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookCtype }
     *     
     */
    public void setBook(BookCtype value) {
        this.book = value;
    }

    /**
     * Gets the value of the editedBook property.
     * 
     * @return
     *     possible object is
     *     {@link EditedBookCtype }
     *     
     */
    public EditedBookCtype getEditedBook() {
        return editedBook;
    }

    /**
     * Sets the value of the editedBook property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditedBookCtype }
     *     
     */
    public void setEditedBook(EditedBookCtype value) {
        this.editedBook = value;
    }

    /**
     * Gets the value of the bookChapter property.
     * 
     * @return
     *     possible object is
     *     {@link BookChapterCtype }
     *     
     */
    public BookChapterCtype getBookChapter() {
        return bookChapter;
    }

    /**
     * Sets the value of the bookChapter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookChapterCtype }
     *     
     */
    public void setBookChapter(BookChapterCtype value) {
        this.bookChapter = value;
    }

    /**
     * Gets the value of the bookReview property.
     * 
     * @return
     *     possible object is
     *     {@link BookReviewCtype }
     *     
     */
    public BookReviewCtype getBookReview() {
        return bookReview;
    }

    /**
     * Sets the value of the bookReview property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookReviewCtype }
     *     
     */
    public void setBookReview(BookReviewCtype value) {
        this.bookReview = value;
    }

    /**
     * Gets the value of the translation property.
     * 
     * @return
     *     possible object is
     *     {@link TranslationCtype }
     *     
     */
    public TranslationCtype getTranslation() {
        return translation;
    }

    /**
     * Sets the value of the translation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranslationCtype }
     *     
     */
    public void setTranslation(TranslationCtype value) {
        this.translation = value;
    }

    /**
     * Gets the value of the dissertation property.
     * 
     * @return
     *     possible object is
     *     {@link DissertationCtype }
     *     
     */
    public DissertationCtype getDissertation() {
        return dissertation;
    }

    /**
     * Sets the value of the dissertation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DissertationCtype }
     *     
     */
    public void setDissertation(DissertationCtype value) {
        this.dissertation = value;
    }

    /**
     * Gets the value of the newspapperArticle property.
     * 
     * @return
     *     possible object is
     *     {@link NewspapperArticleCtype }
     *     
     */
    public NewspapperArticleCtype getNewspapperArticle() {
        return newspapperArticle;
    }

    /**
     * Sets the value of the newspapperArticle property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewspapperArticleCtype }
     *     
     */
    public void setNewspapperArticle(NewspapperArticleCtype value) {
        this.newspapperArticle = value;
    }

    /**
     * Gets the value of the newsletterArticle property.
     * 
     * @return
     *     possible object is
     *     {@link NewsletterArticleCtype }
     *     
     */
    public NewsletterArticleCtype getNewsletterArticle() {
        return newsletterArticle;
    }

    /**
     * Sets the value of the newsletterArticle property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewsletterArticleCtype }
     *     
     */
    public void setNewsletterArticle(NewsletterArticleCtype value) {
        this.newsletterArticle = value;
    }

    /**
     * Gets the value of the encyclopediaEntry property.
     * 
     * @return
     *     possible object is
     *     {@link EncyclopediaEntryCtype }
     *     
     */
    public EncyclopediaEntryCtype getEncyclopediaEntry() {
        return encyclopediaEntry;
    }

    /**
     * Sets the value of the encyclopediaEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncyclopediaEntryCtype }
     *     
     */
    public void setEncyclopediaEntry(EncyclopediaEntryCtype value) {
        this.encyclopediaEntry = value;
    }

    /**
     * Gets the value of the magazineArticle property.
     * 
     * @return
     *     possible object is
     *     {@link MagazineArticleCtype }
     *     
     */
    public MagazineArticleCtype getMagazineArticle() {
        return magazineArticle;
    }

    /**
     * Sets the value of the magazineArticle property.
     * 
     * @param value
     *     allowed object is
     *     {@link MagazineArticleCtype }
     *     
     */
    public void setMagazineArticle(MagazineArticleCtype value) {
        this.magazineArticle = value;
    }

    /**
     * Gets the value of the dictionaryEntry property.
     * 
     * @return
     *     possible object is
     *     {@link DictionaryEntryCtype }
     *     
     */
    public DictionaryEntryCtype getDictionaryEntry() {
        return dictionaryEntry;
    }

    /**
     * Sets the value of the dictionaryEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictionaryEntryCtype }
     *     
     */
    public void setDictionaryEntry(DictionaryEntryCtype value) {
        this.dictionaryEntry = value;
    }

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link ReportCtype }
     *     
     */
    public ReportCtype getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportCtype }
     *     
     */
    public void setReport(ReportCtype value) {
        this.report = value;
    }

    /**
     * Gets the value of the workingPaper property.
     * 
     * @return
     *     possible object is
     *     {@link WorkingPaperCtype }
     *     
     */
    public WorkingPaperCtype getWorkingPaper() {
        return workingPaper;
    }

    /**
     * Sets the value of the workingPaper property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkingPaperCtype }
     *     
     */
    public void setWorkingPaper(WorkingPaperCtype value) {
        this.workingPaper = value;
    }

    /**
     * Gets the value of the manual property.
     * 
     * @return
     *     possible object is
     *     {@link ManualCtype }
     *     
     */
    public ManualCtype getManual() {
        return manual;
    }

    /**
     * Sets the value of the manual property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManualCtype }
     *     
     */
    public void setManual(ManualCtype value) {
        this.manual = value;
    }

    /**
     * Gets the value of the onlineResource property.
     * 
     * @return
     *     possible object is
     *     {@link OnlineResourceCtype }
     *     
     */
    public OnlineResourceCtype getOnlineResource() {
        return onlineResource;
    }

    /**
     * Sets the value of the onlineResource property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnlineResourceCtype }
     *     
     */
    public void setOnlineResource(OnlineResourceCtype value) {
        this.onlineResource = value;
    }

    /**
     * Gets the value of the test property.
     * 
     * @return
     *     possible object is
     *     {@link TestCtype }
     *     
     */
    public TestCtype getTest() {
        return test;
    }

    /**
     * Sets the value of the test property.
     * 
     * @param value
     *     allowed object is
     *     {@link TestCtype }
     *     
     */
    public void setTest(TestCtype value) {
        this.test = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link WebsiteCtype }
     *     
     */
    public WebsiteCtype getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebsiteCtype }
     *     
     */
    public void setWebsite(WebsiteCtype value) {
        this.website = value;
    }

    /**
     * Gets the value of the conferencePaper property.
     * 
     * @return
     *     possible object is
     *     {@link ConferencePaperCtype }
     *     
     */
    public ConferencePaperCtype getConferencePaper() {
        return conferencePaper;
    }

    /**
     * Sets the value of the conferencePaper property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConferencePaperCtype }
     *     
     */
    public void setConferencePaper(ConferencePaperCtype value) {
        this.conferencePaper = value;
    }

    /**
     * Gets the value of the conferenceAbstract property.
     * 
     * @return
     *     possible object is
     *     {@link ConferenceAbstractCtype }
     *     
     */
    public ConferenceAbstractCtype getConferenceAbstract() {
        return conferenceAbstract;
    }

    /**
     * Sets the value of the conferenceAbstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConferenceAbstractCtype }
     *     
     */
    public void setConferenceAbstract(ConferenceAbstractCtype value) {
        this.conferenceAbstract = value;
    }

    /**
     * Gets the value of the conferencePoster property.
     * 
     * @return
     *     possible object is
     *     {@link ConferencePosterCtype }
     *     
     */
    public ConferencePosterCtype getConferencePoster() {
        return conferencePoster;
    }

    /**
     * Sets the value of the conferencePoster property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConferencePosterCtype }
     *     
     */
    public void setConferencePoster(ConferencePosterCtype value) {
        this.conferencePoster = value;
    }

    /**
     * Gets the value of the exhibitionCatalogue property.
     * 
     * @return
     *     possible object is
     *     {@link ExhibitionCatalogueCtype }
     *     
     */
    public ExhibitionCatalogueCtype getExhibitionCatalogue() {
        return exhibitionCatalogue;
    }

    /**
     * Sets the value of the exhibitionCatalogue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExhibitionCatalogueCtype }
     *     
     */
    public void setExhibitionCatalogue(ExhibitionCatalogueCtype value) {
        this.exhibitionCatalogue = value;
    }

    /**
     * Gets the value of the prefacePostface property.
     * 
     * @return
     *     possible object is
     *     {@link PrefacePostfaceCtype }
     *     
     */
    public PrefacePostfaceCtype getPrefacePostface() {
        return prefacePostface;
    }

    /**
     * Sets the value of the prefacePostface property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrefacePostfaceCtype }
     *     
     */
    public void setPrefacePostface(PrefacePostfaceCtype value) {
        this.prefacePostface = value;
    }

    /**
     * Gets the value of the artisticExhibition property.
     * 
     * @return
     *     possible object is
     *     {@link ArtisticExhibitionCtype }
     *     
     */
    public ArtisticExhibitionCtype getArtisticExhibition() {
        return artisticExhibition;
    }

    /**
     * Sets the value of the artisticExhibition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArtisticExhibitionCtype }
     *     
     */
    public void setArtisticExhibition(ArtisticExhibitionCtype value) {
        this.artisticExhibition = value;
    }

    /**
     * Gets the value of the audioRecording property.
     * 
     * @return
     *     possible object is
     *     {@link AudioRecordingCtype }
     *     
     */
    public AudioRecordingCtype getAudioRecording() {
        return audioRecording;
    }

    /**
     * Sets the value of the audioRecording property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioRecordingCtype }
     *     
     */
    public void setAudioRecording(AudioRecordingCtype value) {
        this.audioRecording = value;
    }

    /**
     * Gets the value of the musicalComposition property.
     * 
     * @return
     *     possible object is
     *     {@link MusicalCompositionCtype }
     *     
     */
    public MusicalCompositionCtype getMusicalComposition() {
        return musicalComposition;
    }

    /**
     * Sets the value of the musicalComposition property.
     * 
     * @param value
     *     allowed object is
     *     {@link MusicalCompositionCtype }
     *     
     */
    public void setMusicalComposition(MusicalCompositionCtype value) {
        this.musicalComposition = value;
    }

    /**
     * Gets the value of the musicalPerformance property.
     * 
     * @return
     *     possible object is
     *     {@link MusicalPerformanceCtype }
     *     
     */
    public MusicalPerformanceCtype getMusicalPerformance() {
        return musicalPerformance;
    }

    /**
     * Sets the value of the musicalPerformance property.
     * 
     * @param value
     *     allowed object is
     *     {@link MusicalPerformanceCtype }
     *     
     */
    public void setMusicalPerformance(MusicalPerformanceCtype value) {
        this.musicalPerformance = value;
    }

    /**
     * Gets the value of the radioTvProgram property.
     * 
     * @return
     *     possible object is
     *     {@link RadioTvProgramCtype }
     *     
     */
    public RadioTvProgramCtype getRadioTvProgram() {
        return radioTvProgram;
    }

    /**
     * Sets the value of the radioTvProgram property.
     * 
     * @param value
     *     allowed object is
     *     {@link RadioTvProgramCtype }
     *     
     */
    public void setRadioTvProgram(RadioTvProgramCtype value) {
        this.radioTvProgram = value;
    }

    /**
     * Gets the value of the script property.
     * 
     * @return
     *     possible object is
     *     {@link ScriptCtype }
     *     
     */
    public ScriptCtype getScript() {
        return script;
    }

    /**
     * Sets the value of the script property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScriptCtype }
     *     
     */
    public void setScript(ScriptCtype value) {
        this.script = value;
    }

    /**
     * Gets the value of the shortFiction property.
     * 
     * @return
     *     possible object is
     *     {@link ShortFictionCtype }
     *     
     */
    public ShortFictionCtype getShortFiction() {
        return shortFiction;
    }

    /**
     * Sets the value of the shortFiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShortFictionCtype }
     *     
     */
    public void setShortFiction(ShortFictionCtype value) {
        this.shortFiction = value;
    }

    /**
     * Gets the value of the theatric property.
     * 
     * @return
     *     possible object is
     *     {@link TheatricCtype }
     *     
     */
    public TheatricCtype getTheatric() {
        return theatric;
    }

    /**
     * Sets the value of the theatric property.
     * 
     * @param value
     *     allowed object is
     *     {@link TheatricCtype }
     *     
     */
    public void setTheatric(TheatricCtype value) {
        this.theatric = value;
    }

    /**
     * Gets the value of the videoRecording property.
     * 
     * @return
     *     possible object is
     *     {@link VideoRecordingCtype }
     *     
     */
    public VideoRecordingCtype getVideoRecording() {
        return videoRecording;
    }

    /**
     * Sets the value of the videoRecording property.
     * 
     * @param value
     *     allowed object is
     *     {@link VideoRecordingCtype }
     *     
     */
    public void setVideoRecording(VideoRecordingCtype value) {
        this.videoRecording = value;
    }

    /**
     * Gets the value of the visualArtwork property.
     * 
     * @return
     *     possible object is
     *     {@link VisualArtworkCtype }
     *     
     */
    public VisualArtworkCtype getVisualArtwork() {
        return visualArtwork;
    }

    /**
     * Sets the value of the visualArtwork property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisualArtworkCtype }
     *     
     */
    public void setVisualArtwork(VisualArtworkCtype value) {
        this.visualArtwork = value;
    }

    /**
     * Gets the value of the soundDesign property.
     * 
     * @return
     *     possible object is
     *     {@link SoundDesignCtype }
     *     
     */
    public SoundDesignCtype getSoundDesign() {
        return soundDesign;
    }

    /**
     * Sets the value of the soundDesign property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoundDesignCtype }
     *     
     */
    public void setSoundDesign(SoundDesignCtype value) {
        this.soundDesign = value;
    }

    /**
     * Gets the value of the setDesign property.
     * 
     * @return
     *     possible object is
     *     {@link SetDesignCtype }
     *     
     */
    public SetDesignCtype getSetDesign() {
        return setDesign;
    }

    /**
     * Sets the value of the setDesign property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetDesignCtype }
     *     
     */
    public void setSetDesign(SetDesignCtype value) {
        this.setDesign = value;
    }

    /**
     * Gets the value of the lightDesign property.
     * 
     * @return
     *     possible object is
     *     {@link LightDesignCtype }
     *     
     */
    public LightDesignCtype getLightDesign() {
        return lightDesign;
    }

    /**
     * Sets the value of the lightDesign property.
     * 
     * @param value
     *     allowed object is
     *     {@link LightDesignCtype }
     *     
     */
    public void setLightDesign(LightDesignCtype value) {
        this.lightDesign = value;
    }

    /**
     * Gets the value of the choreography property.
     * 
     * @return
     *     possible object is
     *     {@link ChoreographyCtype }
     *     
     */
    public ChoreographyCtype getChoreography() {
        return choreography;
    }

    /**
     * Sets the value of the choreography property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChoreographyCtype }
     *     
     */
    public void setChoreography(ChoreographyCtype value) {
        this.choreography = value;
    }

    /**
     * Gets the value of the curatorialMuseumExhibition property.
     * 
     * @return
     *     possible object is
     *     {@link CuratorialMuseumExhibitionCtype }
     *     
     */
    public CuratorialMuseumExhibitionCtype getCuratorialMuseumExhibition() {
        return curatorialMuseumExhibition;
    }

    /**
     * Sets the value of the curatorialMuseumExhibition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CuratorialMuseumExhibitionCtype }
     *     
     */
    public void setCuratorialMuseumExhibition(CuratorialMuseumExhibitionCtype value) {
        this.curatorialMuseumExhibition = value;
    }

    /**
     * Gets the value of the performanceArt property.
     * 
     * @return
     *     possible object is
     *     {@link PerformanceArtCtype }
     *     
     */
    public PerformanceArtCtype getPerformanceArt() {
        return performanceArt;
    }

    /**
     * Sets the value of the performanceArt property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerformanceArtCtype }
     *     
     */
    public void setPerformanceArt(PerformanceArtCtype value) {
        this.performanceArt = value;
    }

    /**
     * Gets the value of the patent property.
     * 
     * @return
     *     possible object is
     *     {@link PatentCtype }
     *     
     */
    public PatentCtype getPatent() {
        return patent;
    }

    /**
     * Sets the value of the patent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatentCtype }
     *     
     */
    public void setPatent(PatentCtype value) {
        this.patent = value;
    }

    /**
     * Gets the value of the license property.
     * 
     * @return
     *     possible object is
     *     {@link LicenseCtype }
     *     
     */
    public LicenseCtype getLicense() {
        return license;
    }

    /**
     * Sets the value of the license property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicenseCtype }
     *     
     */
    public void setLicense(LicenseCtype value) {
        this.license = value;
    }

    /**
     * Gets the value of the disclosure property.
     * 
     * @return
     *     possible object is
     *     {@link DisclosureCtype }
     *     
     */
    public DisclosureCtype getDisclosure() {
        return disclosure;
    }

    /**
     * Sets the value of the disclosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisclosureCtype }
     *     
     */
    public void setDisclosure(DisclosureCtype value) {
        this.disclosure = value;
    }

    /**
     * Gets the value of the registeredCopyright property.
     * 
     * @return
     *     possible object is
     *     {@link RegisteredCopyrightCtype }
     *     
     */
    public RegisteredCopyrightCtype getRegisteredCopyright() {
        return registeredCopyright;
    }

    /**
     * Sets the value of the registeredCopyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisteredCopyrightCtype }
     *     
     */
    public void setRegisteredCopyright(RegisteredCopyrightCtype value) {
        this.registeredCopyright = value;
    }

    /**
     * Gets the value of the trademark property.
     * 
     * @return
     *     possible object is
     *     {@link TrademarkCtype }
     *     
     */
    public TrademarkCtype getTrademark() {
        return trademark;
    }

    /**
     * Sets the value of the trademark property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrademarkCtype }
     *     
     */
    public void setTrademark(TrademarkCtype value) {
        this.trademark = value;
    }

    /**
     * Gets the value of the standardOrPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link StandardOrPolicyCtype }
     *     
     */
    public StandardOrPolicyCtype getStandardOrPolicy() {
        return standardOrPolicy;
    }

    /**
     * Sets the value of the standardOrPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardOrPolicyCtype }
     *     
     */
    public void setStandardOrPolicy(StandardOrPolicyCtype value) {
        this.standardOrPolicy = value;
    }

    /**
     * Gets the value of the invention property.
     * 
     * @return
     *     possible object is
     *     {@link InventionCtype }
     *     
     */
    public InventionCtype getInvention() {
        return invention;
    }

    /**
     * Sets the value of the invention property.
     * 
     * @param value
     *     allowed object is
     *     {@link InventionCtype }
     *     
     */
    public void setInvention(InventionCtype value) {
        this.invention = value;
    }

    /**
     * Gets the value of the dataSet property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetCtype }
     *     
     */
    public DataSetCtype getDataSet() {
        return dataSet;
    }

    /**
     * Sets the value of the dataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetCtype }
     *     
     */
    public void setDataSet(DataSetCtype value) {
        this.dataSet = value;
    }

    /**
     * Gets the value of the litigation property.
     * 
     * @return
     *     possible object is
     *     {@link LitigationCtype }
     *     
     */
    public LitigationCtype getLitigation() {
        return litigation;
    }

    /**
     * Sets the value of the litigation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LitigationCtype }
     *     
     */
    public void setLitigation(LitigationCtype value) {
        this.litigation = value;
    }

    /**
     * Gets the value of the researchTechnique property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchTechniqueCtype }
     *     
     */
    public ResearchTechniqueCtype getResearchTechnique() {
        return researchTechnique;
    }

    /**
     * Sets the value of the researchTechnique property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchTechniqueCtype }
     *     
     */
    public void setResearchTechnique(ResearchTechniqueCtype value) {
        this.researchTechnique = value;
    }

    /**
     * Gets the value of the spinOffCompany property.
     * 
     * @return
     *     possible object is
     *     {@link SpinOffCompanyCtype }
     *     
     */
    public SpinOffCompanyCtype getSpinOffCompany() {
        return spinOffCompany;
    }

    /**
     * Sets the value of the spinOffCompany property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpinOffCompanyCtype }
     *     
     */
    public void setSpinOffCompany(SpinOffCompanyCtype value) {
        this.spinOffCompany = value;
    }

    /**
     * Gets the value of the technicalStandard property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalStandardCtype }
     *     
     */
    public TechnicalStandardCtype getTechnicalStandard() {
        return technicalStandard;
    }

    /**
     * Sets the value of the technicalStandard property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalStandardCtype }
     *     
     */
    public void setTechnicalStandard(TechnicalStandardCtype value) {
        this.technicalStandard = value;
    }

    /**
     * Gets the value of the otherOutput property.
     * 
     * @return
     *     possible object is
     *     {@link OtherOutputCtype }
     *     
     */
    public OtherOutputCtype getOtherOutput() {
        return otherOutput;
    }

    /**
     * Sets the value of the otherOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherOutputCtype }
     *     
     */
    public void setOtherOutput(OtherOutputCtype value) {
        this.otherOutput = value;
    }

}
