//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.degree;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.DateCtype;
import pt.cienciavitae.ns.common.InstitutionsCtype;
import pt.cienciavitae.ns.common.RecordCtype;
import pt.cienciavitae.ns.common.ResearchClassificationsCtype;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.cienciavitae.pt/ns/common}record-ctype"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="degree-type" type="{http://www.cienciavitae.pt/ns/degree}degree-type-ctype"/&gt;
 *         &lt;element name="degree-code" type="{http://www.cienciavitae.pt/ns/degree}degree-code-ctype" minOccurs="0"/&gt;
 *         &lt;element name="degree-name" type="{http://www.cienciavitae.pt/ns/common}string-255-stype"/&gt;
 *         &lt;element ref="{http://www.cienciavitae.pt/ns/common}institutions"/&gt;
 *         &lt;element name="degree-major" type="{http://www.cienciavitae.pt/ns/common}string-255-stype" minOccurs="0"/&gt;
 *         &lt;element name="description" type="{http://www.cienciavitae.pt/ns/common}string-255-stype" minOccurs="0"/&gt;
 *         &lt;element name="classification" type="{http://www.cienciavitae.pt/ns/common}string-50-stype" minOccurs="0"/&gt;
 *         &lt;element name="degree-status" type="{http://www.cienciavitae.pt/ns/degree}degree-status-ctype"/&gt;
 *         &lt;element name="start-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *         &lt;element name="end-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype"/&gt;
 *         &lt;element name="thesis" type="{http://www.cienciavitae.pt/ns/degree}thesis-ctype" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cienciavitae.pt/ns/common}research-classifications" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "degreeType",
    "degreeCode",
    "degreeName",
    "institutions",
    "degreeMajor",
    "description",
    "classification",
    "degreeStatus",
    "startDate",
    "endDate",
    "thesis",
    "researchClassifications"
})
@XmlRootElement(name = "degree")
public class Degree
    extends RecordCtype
{

    @XmlElement(name = "degree-type", required = true)
    protected DegreeTypeCtype degreeType;
    @XmlElement(name = "degree-code")
    protected DegreeCodeCtype degreeCode;
    @XmlElement(name = "degree-name", required = true)
    protected String degreeName;
    @XmlElement(namespace = "http://www.cienciavitae.pt/ns/common", required = true)
    protected InstitutionsCtype institutions;
    @XmlElement(name = "degree-major")
    protected String degreeMajor;
    protected String description;
    protected String classification;
    @XmlElement(name = "degree-status", required = true)
    protected DegreeStatusCtype degreeStatus;
    @XmlElement(name = "start-date")
    protected DateCtype startDate;
    @XmlElement(name = "end-date", required = true)
    protected DateCtype endDate;
    protected ThesisCtype thesis;
    @XmlElement(name = "research-classifications", namespace = "http://www.cienciavitae.pt/ns/common")
    protected ResearchClassificationsCtype researchClassifications;

    /**
     * Gets the value of the degreeType property.
     * 
     * @return
     *     possible object is
     *     {@link DegreeTypeCtype }
     *     
     */
    public DegreeTypeCtype getDegreeType() {
        return degreeType;
    }

    /**
     * Sets the value of the degreeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DegreeTypeCtype }
     *     
     */
    public void setDegreeType(DegreeTypeCtype value) {
        this.degreeType = value;
    }

    /**
     * Gets the value of the degreeCode property.
     * 
     * @return
     *     possible object is
     *     {@link DegreeCodeCtype }
     *     
     */
    public DegreeCodeCtype getDegreeCode() {
        return degreeCode;
    }

    /**
     * Sets the value of the degreeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link DegreeCodeCtype }
     *     
     */
    public void setDegreeCode(DegreeCodeCtype value) {
        this.degreeCode = value;
    }

    /**
     * Gets the value of the degreeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegreeName() {
        return degreeName;
    }

    /**
     * Sets the value of the degreeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegreeName(String value) {
        this.degreeName = value;
    }

    /**
     * Gets the value of the institutions property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionsCtype }
     *     
     */
    public InstitutionsCtype getInstitutions() {
        return institutions;
    }

    /**
     * Sets the value of the institutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionsCtype }
     *     
     */
    public void setInstitutions(InstitutionsCtype value) {
        this.institutions = value;
    }

    /**
     * Gets the value of the degreeMajor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegreeMajor() {
        return degreeMajor;
    }

    /**
     * Sets the value of the degreeMajor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegreeMajor(String value) {
        this.degreeMajor = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassification(String value) {
        this.classification = value;
    }

    /**
     * Gets the value of the degreeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DegreeStatusCtype }
     *     
     */
    public DegreeStatusCtype getDegreeStatus() {
        return degreeStatus;
    }

    /**
     * Sets the value of the degreeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DegreeStatusCtype }
     *     
     */
    public void setDegreeStatus(DegreeStatusCtype value) {
        this.degreeStatus = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setStartDate(DateCtype value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setEndDate(DateCtype value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the thesis property.
     * 
     * @return
     *     possible object is
     *     {@link ThesisCtype }
     *     
     */
    public ThesisCtype getThesis() {
        return thesis;
    }

    /**
     * Sets the value of the thesis property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThesisCtype }
     *     
     */
    public void setThesis(ThesisCtype value) {
        this.thesis = value;
    }

    /**
     * Gets the value of the researchClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public ResearchClassificationsCtype getResearchClassifications() {
        return researchClassifications;
    }

    /**
     * Sets the value of the researchClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public void setResearchClassifications(ResearchClassificationsCtype value) {
        this.researchClassifications = value;
    }

}
