//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.statistic;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="persons" type="{http://www.cienciavitae.pt/ns/statistic}total-ctype"/&gt;
 *         &lt;element name="projects" type="{http://www.cienciavitae.pt/ns/statistic}total-ctype"/&gt;
 *         &lt;element name="journal-articles" type="{http://www.cienciavitae.pt/ns/statistic}total-ctype"/&gt;
 *         &lt;element name="institutions" type="{http://www.cienciavitae.pt/ns/statistic}total-ctype"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "persons",
    "projects",
    "journalArticles",
    "institutions"
})
@XmlRootElement(name = "statistics")
public class Statistics {

    @XmlElement(required = true)
    protected TotalCtype persons;
    @XmlElement(required = true)
    protected TotalCtype projects;
    @XmlElement(name = "journal-articles", required = true)
    protected TotalCtype journalArticles;
    @XmlElement(required = true)
    protected TotalCtype institutions;

    /**
     * Gets the value of the persons property.
     * 
     * @return
     *     possible object is
     *     {@link TotalCtype }
     *     
     */
    public TotalCtype getPersons() {
        return persons;
    }

    /**
     * Sets the value of the persons property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalCtype }
     *     
     */
    public void setPersons(TotalCtype value) {
        this.persons = value;
    }

    /**
     * Gets the value of the projects property.
     * 
     * @return
     *     possible object is
     *     {@link TotalCtype }
     *     
     */
    public TotalCtype getProjects() {
        return projects;
    }

    /**
     * Sets the value of the projects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalCtype }
     *     
     */
    public void setProjects(TotalCtype value) {
        this.projects = value;
    }

    /**
     * Gets the value of the journalArticles property.
     * 
     * @return
     *     possible object is
     *     {@link TotalCtype }
     *     
     */
    public TotalCtype getJournalArticles() {
        return journalArticles;
    }

    /**
     * Sets the value of the journalArticles property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalCtype }
     *     
     */
    public void setJournalArticles(TotalCtype value) {
        this.journalArticles = value;
    }

    /**
     * Gets the value of the institutions property.
     * 
     * @return
     *     possible object is
     *     {@link TotalCtype }
     *     
     */
    public TotalCtype getInstitutions() {
        return institutions;
    }

    /**
     * Sets the value of the institutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalCtype }
     *     
     */
    public void setInstitutions(TotalCtype value) {
        this.institutions = value;
    }

}
