//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import pt.cienciavitae.ns.common.DateCtype;
import pt.cienciavitae.ns.common.InstitutionsCtype;


/**
 * Corresponding to "service:service-category[@code='S110']"
 * 
 * <p>Java class for research-based-degree-supervision-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="research-based-degree-supervision-ctype"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="start-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype"/&gt;
 *         &lt;element name="end-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *         &lt;element name="tid" type="{http://www.cienciavitae.pt/ns/common}string-15-stype" minOccurs="0"/&gt;
 *         &lt;element name="thesis-title" type="{http://www.cienciavitae.pt/ns/common}string-555-stype"/&gt;
 *         &lt;element name="student-name"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.cienciavitae.pt/ns/common&gt;string-120-stype"&gt;
 *                 &lt;attribute name="consent-obtained-for-name-release" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="degree-subject" type="{http://www.cienciavitae.pt/ns/common}string-255-stype" minOccurs="0"/&gt;
 *         &lt;element name="degree-type" type="{http://www.cienciavitae.pt/ns/service}degree-type-ctype" minOccurs="0"/&gt;
 *         &lt;element name="course-code" type="{http://www.cienciavitae.pt/ns/service}course-code-ctype" minOccurs="0"/&gt;
 *         &lt;element name="degree-status" type="{http://www.cienciavitae.pt/ns/service}degree-status-ctype" minOccurs="0"/&gt;
 *         &lt;element name="supervisory-type" type="{http://www.cienciavitae.pt/ns/service}supervisory-type-ctype" minOccurs="0"/&gt;
 *         &lt;element name="url" type="{http://www.cienciavitae.pt/ns/common}string-uri-stype" minOccurs="0"/&gt;
 *         &lt;element name="academic-institutions" type="{http://www.cienciavitae.pt/ns/common}institutions-ctype" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "research-based-degree-supervision-ctype", propOrder = {
    "startDate",
    "endDate",
    "tid",
    "thesisTitle",
    "studentName",
    "degreeSubject",
    "degreeType",
    "courseCode",
    "degreeStatus",
    "supervisoryType",
    "url",
    "academicInstitutions"
})
public class ResearchBasedDegreeSupervisionCtype {

    @XmlElement(name = "start-date", required = true)
    protected DateCtype startDate;
    @XmlElement(name = "end-date")
    protected DateCtype endDate;
    protected String tid;
    @XmlElement(name = "thesis-title", required = true)
    protected String thesisTitle;
    @XmlElement(name = "student-name", required = true)
    protected ResearchBasedDegreeSupervisionCtype.StudentName studentName;
    @XmlElement(name = "degree-subject")
    protected String degreeSubject;
    @XmlElement(name = "degree-type")
    protected DegreeTypeCtype degreeType;
    @XmlElement(name = "course-code")
    protected CourseCodeCtype courseCode;
    @XmlElement(name = "degree-status")
    protected DegreeStatusCtype degreeStatus;
    @XmlElement(name = "supervisory-type")
    protected SupervisoryTypeCtype supervisoryType;
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlElement(name = "academic-institutions")
    protected InstitutionsCtype academicInstitutions;

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setStartDate(DateCtype value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setEndDate(DateCtype value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the tid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTid() {
        return tid;
    }

    /**
     * Sets the value of the tid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTid(String value) {
        this.tid = value;
    }

    /**
     * Gets the value of the thesisTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThesisTitle() {
        return thesisTitle;
    }

    /**
     * Sets the value of the thesisTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThesisTitle(String value) {
        this.thesisTitle = value;
    }

    /**
     * Gets the value of the studentName property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchBasedDegreeSupervisionCtype.StudentName }
     *     
     */
    public ResearchBasedDegreeSupervisionCtype.StudentName getStudentName() {
        return studentName;
    }

    /**
     * Sets the value of the studentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchBasedDegreeSupervisionCtype.StudentName }
     *     
     */
    public void setStudentName(ResearchBasedDegreeSupervisionCtype.StudentName value) {
        this.studentName = value;
    }

    /**
     * Gets the value of the degreeSubject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegreeSubject() {
        return degreeSubject;
    }

    /**
     * Sets the value of the degreeSubject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegreeSubject(String value) {
        this.degreeSubject = value;
    }

    /**
     * Gets the value of the degreeType property.
     * 
     * @return
     *     possible object is
     *     {@link DegreeTypeCtype }
     *     
     */
    public DegreeTypeCtype getDegreeType() {
        return degreeType;
    }

    /**
     * Sets the value of the degreeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DegreeTypeCtype }
     *     
     */
    public void setDegreeType(DegreeTypeCtype value) {
        this.degreeType = value;
    }

    /**
     * Gets the value of the courseCode property.
     * 
     * @return
     *     possible object is
     *     {@link CourseCodeCtype }
     *     
     */
    public CourseCodeCtype getCourseCode() {
        return courseCode;
    }

    /**
     * Sets the value of the courseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseCodeCtype }
     *     
     */
    public void setCourseCode(CourseCodeCtype value) {
        this.courseCode = value;
    }

    /**
     * Gets the value of the degreeStatus property.
     * 
     * @return
     *     possible object is
     *     {@link DegreeStatusCtype }
     *     
     */
    public DegreeStatusCtype getDegreeStatus() {
        return degreeStatus;
    }

    /**
     * Sets the value of the degreeStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link DegreeStatusCtype }
     *     
     */
    public void setDegreeStatus(DegreeStatusCtype value) {
        this.degreeStatus = value;
    }

    /**
     * Gets the value of the supervisoryType property.
     * 
     * @return
     *     possible object is
     *     {@link SupervisoryTypeCtype }
     *     
     */
    public SupervisoryTypeCtype getSupervisoryType() {
        return supervisoryType;
    }

    /**
     * Sets the value of the supervisoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupervisoryTypeCtype }
     *     
     */
    public void setSupervisoryType(SupervisoryTypeCtype value) {
        this.supervisoryType = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the academicInstitutions property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionsCtype }
     *     
     */
    public InstitutionsCtype getAcademicInstitutions() {
        return academicInstitutions;
    }

    /**
     * Sets the value of the academicInstitutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionsCtype }
     *     
     */
    public void setAcademicInstitutions(InstitutionsCtype value) {
        this.academicInstitutions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.cienciavitae.pt/ns/common&gt;string-120-stype"&gt;
     *       &lt;attribute name="consent-obtained-for-name-release" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StudentName {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "consent-obtained-for-name-release", required = true)
        protected boolean consentObtainedForNameRelease;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the consentObtainedForNameRelease property.
         * 
         */
        public boolean isConsentObtainedForNameRelease() {
            return consentObtainedForNameRelease;
        }

        /**
         * Sets the value of the consentObtainedForNameRelease property.
         * 
         */
        public void setConsentObtainedForNameRelease(boolean value) {
            this.consentObtainedForNameRelease = value;
        }

    }

}
