//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.groups;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.DateCtype;


/**
 * <p>Java class for employment-service-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="employment-service-ctype"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="employment"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="employment-category" type="{http://www.cienciavitae.pt/ns/common}string-100-stype" minOccurs="0"/&gt;
 *                   &lt;element name="position-type" type="{http://www.cienciavitae.pt/ns/common}string-100-stype" minOccurs="0"/&gt;
 *                   &lt;element name="position-title" type="{http://www.cienciavitae.pt/ns/common}string-100-stype" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.cienciavitae.pt/ns/common}id-stype" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="service"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="description" type="{http://www.cienciavitae.pt/ns/common}string-555-stype" minOccurs="0"/&gt;
 *                   &lt;element name="start-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *                   &lt;element name="end-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.cienciavitae.pt/ns/common}id-stype" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "employment-service-ctype", propOrder = {
    "employment",
    "service"
})
public class EmploymentServiceCtype {

    @XmlElement(required = true)
    protected EmploymentServiceCtype.Employment employment;
    @XmlElement(required = true)
    protected EmploymentServiceCtype.Service service;

    /**
     * Gets the value of the employment property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentServiceCtype.Employment }
     *     
     */
    public EmploymentServiceCtype.Employment getEmployment() {
        return employment;
    }

    /**
     * Sets the value of the employment property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentServiceCtype.Employment }
     *     
     */
    public void setEmployment(EmploymentServiceCtype.Employment value) {
        this.employment = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentServiceCtype.Service }
     *     
     */
    public EmploymentServiceCtype.Service getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentServiceCtype.Service }
     *     
     */
    public void setService(EmploymentServiceCtype.Service value) {
        this.service = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="employment-category" type="{http://www.cienciavitae.pt/ns/common}string-100-stype" minOccurs="0"/&gt;
     *         &lt;element name="position-type" type="{http://www.cienciavitae.pt/ns/common}string-100-stype" minOccurs="0"/&gt;
     *         &lt;element name="position-title" type="{http://www.cienciavitae.pt/ns/common}string-100-stype" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.cienciavitae.pt/ns/common}id-stype" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "employmentCategory",
        "positionType",
        "positionTitle"
    })
    public static class Employment {

        @XmlElement(name = "employment-category")
        protected String employmentCategory;
        @XmlElement(name = "position-type")
        protected String positionType;
        @XmlElement(name = "position-title")
        protected String positionTitle;
        @XmlAttribute(name = "id", required = true)
        protected int id;

        /**
         * Gets the value of the employmentCategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmploymentCategory() {
            return employmentCategory;
        }

        /**
         * Sets the value of the employmentCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmploymentCategory(String value) {
            this.employmentCategory = value;
        }

        /**
         * Gets the value of the positionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPositionType() {
            return positionType;
        }

        /**
         * Sets the value of the positionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPositionType(String value) {
            this.positionType = value;
        }

        /**
         * Gets the value of the positionTitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPositionTitle() {
            return positionTitle;
        }

        /**
         * Sets the value of the positionTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPositionTitle(String value) {
            this.positionTitle = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="description" type="{http://www.cienciavitae.pt/ns/common}string-555-stype" minOccurs="0"/&gt;
     *         &lt;element name="start-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
     *         &lt;element name="end-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.cienciavitae.pt/ns/common}id-stype" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "startDate",
        "endDate"
    })
    public static class Service {

        protected String description;
        @XmlElement(name = "start-date")
        protected DateCtype startDate;
        @XmlElement(name = "end-date")
        protected DateCtype endDate;
        @XmlAttribute(name = "id", required = true)
        protected int id;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the startDate property.
         * 
         * @return
         *     possible object is
         *     {@link DateCtype }
         *     
         */
        public DateCtype getStartDate() {
            return startDate;
        }

        /**
         * Sets the value of the startDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateCtype }
         *     
         */
        public void setStartDate(DateCtype value) {
            this.startDate = value;
        }

        /**
         * Gets the value of the endDate property.
         * 
         * @return
         *     possible object is
         *     {@link DateCtype }
         *     
         */
        public DateCtype getEndDate() {
            return endDate;
        }

        /**
         * Sets the value of the endDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link DateCtype }
         *     
         */
        public void setEndDate(DateCtype value) {
            this.endDate = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

    }

}
