//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.mailing_address;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.ContactTypeCtype;
import pt.cienciavitae.ns.common.Iso3166CountryCtype;
import pt.cienciavitae.ns.common.RecordCtype;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.cienciavitae.pt/ns/common}record-ctype"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="address-type" type="{http://www.cienciavitae.pt/ns/common}contact-type-ctype"/&gt;
 *         &lt;element name="street-address" type="{http://www.cienciavitae.pt/ns/common}string-255-stype"/&gt;
 *         &lt;element name="postal-code" type="{http://www.cienciavitae.pt/ns/common}string-10-stype"/&gt;
 *         &lt;element name="city" type="{http://www.cienciavitae.pt/ns/common}string-50-stype"/&gt;
 *         &lt;element name="province-state" type="{http://www.cienciavitae.pt/ns/common}string-50-stype"/&gt;
 *         &lt;element name="country" type="{http://www.cienciavitae.pt/ns/common}iso-3166-country-ctype"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="preferred-mailing-address" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addressType",
    "streetAddress",
    "postalCode",
    "city",
    "provinceState",
    "country"
})
@XmlRootElement(name = "mailing-address")
public class MailingAddress
    extends RecordCtype
{

    @XmlElement(name = "address-type", required = true)
    protected ContactTypeCtype addressType;
    @XmlElement(name = "street-address", required = true)
    protected String streetAddress;
    @XmlElement(name = "postal-code", required = true)
    protected String postalCode;
    @XmlElement(required = true)
    protected String city;
    @XmlElement(name = "province-state", required = true)
    protected String provinceState;
    @XmlElement(required = true)
    protected Iso3166CountryCtype country;
    @XmlAttribute(name = "preferred-mailing-address")
    protected Boolean preferredMailingAddress;

    /**
     * Gets the value of the addressType property.
     * 
     * @return
     *     possible object is
     *     {@link ContactTypeCtype }
     *     
     */
    public ContactTypeCtype getAddressType() {
        return addressType;
    }

    /**
     * Sets the value of the addressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactTypeCtype }
     *     
     */
    public void setAddressType(ContactTypeCtype value) {
        this.addressType = value;
    }

    /**
     * Gets the value of the streetAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetAddress() {
        return streetAddress;
    }

    /**
     * Sets the value of the streetAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetAddress(String value) {
        this.streetAddress = value;
    }

    /**
     * Gets the value of the postalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * Sets the value of the postalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostalCode(String value) {
        this.postalCode = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the provinceState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvinceState() {
        return provinceState;
    }

    /**
     * Sets the value of the provinceState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvinceState(String value) {
        this.provinceState = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link Iso3166CountryCtype }
     *     
     */
    public Iso3166CountryCtype getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link Iso3166CountryCtype }
     *     
     */
    public void setCountry(Iso3166CountryCtype value) {
        this.country = value;
    }

    /**
     * Gets the value of the preferredMailingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPreferredMailingAddress() {
        if (preferredMailingAddress == null) {
            return false;
        } else {
            return preferredMailingAddress;
        }
    }

    /**
     * Sets the value of the preferredMailingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreferredMailingAddress(Boolean value) {
        this.preferredMailingAddress = value;
    }

}
