//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for institution-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="institution-ctype"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="institution-name" type="{http://www.cienciavitae.pt/ns/common}string-255-stype"/&gt;
 *         &lt;element name="institution-address" type="{http://www.cienciavitae.pt/ns/common}institution-address-ctype"/&gt;
 *         &lt;element name="institution-sector" type="{http://www.cienciavitae.pt/ns/common}institution-sector-ctype"/&gt;
 *         &lt;element name="institution-identifier" type="{http://www.cienciavitae.pt/ns/common}institution-identifier-ctype" minOccurs="0"/&gt;
 *         &lt;element name="institution-other-identifiers" type="{http://www.cienciavitae.pt/ns/common}institution-identifiers-ctype" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "institution-ctype", propOrder = {
    "institutionName",
    "institutionAddress",
    "institutionSector",
    "institutionIdentifier",
    "institutionOtherIdentifiers"
})
public class InstitutionCtype {

    @XmlElement(name = "institution-name", required = true)
    protected String institutionName;
    @XmlElement(name = "institution-address", required = true)
    protected InstitutionAddressCtype institutionAddress;
    @XmlElement(name = "institution-sector", required = true)
    protected InstitutionSectorCtype institutionSector;
    @XmlElement(name = "institution-identifier")
    protected InstitutionIdentifierCtype institutionIdentifier;
    @XmlElement(name = "institution-other-identifiers")
    protected InstitutionIdentifiersCtype institutionOtherIdentifiers;

    /**
     * Gets the value of the institutionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitutionName() {
        return institutionName;
    }

    /**
     * Sets the value of the institutionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitutionName(String value) {
        this.institutionName = value;
    }

    /**
     * Gets the value of the institutionAddress property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionAddressCtype }
     *     
     */
    public InstitutionAddressCtype getInstitutionAddress() {
        return institutionAddress;
    }

    /**
     * Sets the value of the institutionAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionAddressCtype }
     *     
     */
    public void setInstitutionAddress(InstitutionAddressCtype value) {
        this.institutionAddress = value;
    }

    /**
     * Gets the value of the institutionSector property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionSectorCtype }
     *     
     */
    public InstitutionSectorCtype getInstitutionSector() {
        return institutionSector;
    }

    /**
     * Sets the value of the institutionSector property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionSectorCtype }
     *     
     */
    public void setInstitutionSector(InstitutionSectorCtype value) {
        this.institutionSector = value;
    }

    /**
     * Gets the value of the institutionIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionIdentifierCtype }
     *     
     */
    public InstitutionIdentifierCtype getInstitutionIdentifier() {
        return institutionIdentifier;
    }

    /**
     * Sets the value of the institutionIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionIdentifierCtype }
     *     
     */
    public void setInstitutionIdentifier(InstitutionIdentifierCtype value) {
        this.institutionIdentifier = value;
    }

    /**
     * Gets the value of the institutionOtherIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionIdentifiersCtype }
     *     
     */
    public InstitutionIdentifiersCtype getInstitutionOtherIdentifiers() {
        return institutionOtherIdentifiers;
    }

    /**
     * Sets the value of the institutionOtherIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionIdentifiersCtype }
     *     
     */
    public void setInstitutionOtherIdentifiers(InstitutionIdentifiersCtype value) {
        this.institutionOtherIdentifiers = value;
    }

}
