//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pt.cienciavitae.ns.common package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ResearchClassifications_QNAME = new QName("http://www.cienciavitae.pt/ns/common", "research-classifications");
    private final static QName _ResearchClassification_QNAME = new QName("http://www.cienciavitae.pt/ns/common", "research-classification");
    private final static QName _Keywords_QNAME = new QName("http://www.cienciavitae.pt/ns/common", "keywords");
    private final static QName _Keyword_QNAME = new QName("http://www.cienciavitae.pt/ns/common", "keyword");
    private final static QName _Institutions_QNAME = new QName("http://www.cienciavitae.pt/ns/common", "institutions");
    private final static QName _Institution_QNAME = new QName("http://www.cienciavitae.pt/ns/common", "institution");
    private final static QName _FundingInstitutions_QNAME = new QName("http://www.cienciavitae.pt/ns/common", "funding-institutions");
    private final static QName _FundingInstitution_QNAME = new QName("http://www.cienciavitae.pt/ns/common", "funding-institution");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.cienciavitae.ns.common
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrivacyLevelCtype }
     * 
     */
    public PrivacyLevelCtype createPrivacyLevelCtype() {
        return new PrivacyLevelCtype();
    }

    /**
     * Create an instance of {@link RoleCtype }
     * 
     */
    public RoleCtype createRoleCtype() {
        return new RoleCtype();
    }

    /**
     * Create an instance of {@link ResearchClassificationsCtype }
     * 
     */
    public ResearchClassificationsCtype createResearchClassificationsCtype() {
        return new ResearchClassificationsCtype();
    }

    /**
     * Create an instance of {@link ResearchClassificationCtype }
     * 
     */
    public ResearchClassificationCtype createResearchClassificationCtype() {
        return new ResearchClassificationCtype();
    }

    /**
     * Create an instance of {@link KeywordsCtype }
     * 
     */
    public KeywordsCtype createKeywordsCtype() {
        return new KeywordsCtype();
    }

    /**
     * Create an instance of {@link InstitutionsCtype }
     * 
     */
    public InstitutionsCtype createInstitutionsCtype() {
        return new InstitutionsCtype();
    }

    /**
     * Create an instance of {@link InstitutionCtype }
     * 
     */
    public InstitutionCtype createInstitutionCtype() {
        return new InstitutionCtype();
    }

    /**
     * Create an instance of {@link ContainerCtype }
     * 
     */
    public ContainerCtype createContainerCtype() {
        return new ContainerCtype();
    }

    /**
     * Create an instance of {@link ContainerLastdateCtype }
     * 
     */
    public ContainerLastdateCtype createContainerLastdateCtype() {
        return new ContainerLastdateCtype();
    }

    /**
     * Create an instance of {@link VersionContainerCtype }
     * 
     */
    public VersionContainerCtype createVersionContainerCtype() {
        return new VersionContainerCtype();
    }

    /**
     * Create an instance of {@link RecordCtype }
     * 
     */
    public RecordCtype createRecordCtype() {
        return new RecordCtype();
    }

    /**
     * Create an instance of {@link ExtendedRecordCtype }
     * 
     */
    public ExtendedRecordCtype createExtendedRecordCtype() {
        return new ExtendedRecordCtype();
    }

    /**
     * Create an instance of {@link ContactTypeCtype }
     * 
     */
    public ContactTypeCtype createContactTypeCtype() {
        return new ContactTypeCtype();
    }

    /**
     * Create an instance of {@link AuthorsCtype }
     * 
     */
    public AuthorsCtype createAuthorsCtype() {
        return new AuthorsCtype();
    }

    /**
     * Create an instance of {@link AuthorCtype }
     * 
     */
    public AuthorCtype createAuthorCtype() {
        return new AuthorCtype();
    }

    /**
     * Create an instance of {@link SupervisorsCtype }
     * 
     */
    public SupervisorsCtype createSupervisorsCtype() {
        return new SupervisorsCtype();
    }

    /**
     * Create an instance of {@link SupervisorCtype }
     * 
     */
    public SupervisorCtype createSupervisorCtype() {
        return new SupervisorCtype();
    }

    /**
     * Create an instance of {@link SupervisorRoleCtype }
     * 
     */
    public SupervisorRoleCtype createSupervisorRoleCtype() {
        return new SupervisorRoleCtype();
    }

    /**
     * Create an instance of {@link InstitutionIdentifiersCtype }
     * 
     */
    public InstitutionIdentifiersCtype createInstitutionIdentifiersCtype() {
        return new InstitutionIdentifiersCtype();
    }

    /**
     * Create an instance of {@link InstitutionAddressCtype }
     * 
     */
    public InstitutionAddressCtype createInstitutionAddressCtype() {
        return new InstitutionAddressCtype();
    }

    /**
     * Create an instance of {@link InstitutionSectorCtype }
     * 
     */
    public InstitutionSectorCtype createInstitutionSectorCtype() {
        return new InstitutionSectorCtype();
    }

    /**
     * Create an instance of {@link InstitutionIdentifierCtype }
     * 
     */
    public InstitutionIdentifierCtype createInstitutionIdentifierCtype() {
        return new InstitutionIdentifierCtype();
    }

    /**
     * Create an instance of {@link Iso3166CountryCtype }
     * 
     */
    public Iso3166CountryCtype createIso3166CountryCtype() {
        return new Iso3166CountryCtype();
    }

    /**
     * Create an instance of {@link Iso4217CurrencyCtype }
     * 
     */
    public Iso4217CurrencyCtype createIso4217CurrencyCtype() {
        return new Iso4217CurrencyCtype();
    }

    /**
     * Create an instance of {@link IdentifierRelationshipTypeCtype }
     * 
     */
    public IdentifierRelationshipTypeCtype createIdentifierRelationshipTypeCtype() {
        return new IdentifierRelationshipTypeCtype();
    }

    /**
     * Create an instance of {@link DateCtype }
     * 
     */
    public DateCtype createDateCtype() {
        return new DateCtype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResearchClassificationsCtype }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResearchClassificationsCtype }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cienciavitae.pt/ns/common", name = "research-classifications")
    public JAXBElement<ResearchClassificationsCtype> createResearchClassifications(ResearchClassificationsCtype value) {
        return new JAXBElement<ResearchClassificationsCtype>(_ResearchClassifications_QNAME, ResearchClassificationsCtype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResearchClassificationCtype }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ResearchClassificationCtype }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cienciavitae.pt/ns/common", name = "research-classification")
    public JAXBElement<ResearchClassificationCtype> createResearchClassification(ResearchClassificationCtype value) {
        return new JAXBElement<ResearchClassificationCtype>(_ResearchClassification_QNAME, ResearchClassificationCtype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeywordsCtype }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link KeywordsCtype }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cienciavitae.pt/ns/common", name = "keywords")
    public JAXBElement<KeywordsCtype> createKeywords(KeywordsCtype value) {
        return new JAXBElement<KeywordsCtype>(_Keywords_QNAME, KeywordsCtype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cienciavitae.pt/ns/common", name = "keyword")
    public JAXBElement<String> createKeyword(String value) {
        return new JAXBElement<String>(_Keyword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstitutionsCtype }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InstitutionsCtype }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cienciavitae.pt/ns/common", name = "institutions")
    public JAXBElement<InstitutionsCtype> createInstitutions(InstitutionsCtype value) {
        return new JAXBElement<InstitutionsCtype>(_Institutions_QNAME, InstitutionsCtype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstitutionCtype }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InstitutionCtype }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cienciavitae.pt/ns/common", name = "institution")
    public JAXBElement<InstitutionCtype> createInstitution(InstitutionCtype value) {
        return new JAXBElement<InstitutionCtype>(_Institution_QNAME, InstitutionCtype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstitutionsCtype }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InstitutionsCtype }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cienciavitae.pt/ns/common", name = "funding-institutions")
    public JAXBElement<InstitutionsCtype> createFundingInstitutions(InstitutionsCtype value) {
        return new JAXBElement<InstitutionsCtype>(_FundingInstitutions_QNAME, InstitutionsCtype.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstitutionCtype }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link InstitutionCtype }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.cienciavitae.pt/ns/common", name = "funding-institution")
    public JAXBElement<InstitutionCtype> createFundingInstitution(InstitutionCtype value) {
        return new JAXBElement<InstitutionCtype>(_FundingInstitution_QNAME, InstitutionCtype.class, null, value);
    }

}
