//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import pt.cienciavitae.ns.author_identifier.AuthorIdentifier;
import pt.cienciavitae.ns.common_enum.PrivacyLevelEnum;
import pt.cienciavitae.ns.degree.Degree;
import pt.cienciavitae.ns.distinction.Distinction;
import pt.cienciavitae.ns.domain_activity.DomainActivity;
import pt.cienciavitae.ns.email.Email;
import pt.cienciavitae.ns.employment.Employment;
import pt.cienciavitae.ns.language_competency.LanguageCompetency;
import pt.cienciavitae.ns.mailing_address.MailingAddress;
import pt.cienciavitae.ns.phone_number.PhoneNumber;
import pt.cienciavitae.ns.web_address.WebAddress;


/**
 * <p>Java class for record-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="record-ctype"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="id" type="{http://www.cienciavitae.pt/ns/common}id-stype" /&gt;
 *       &lt;attribute name="privacy-level" use="required" type="{http://www.cienciavitae.pt/ns/common-enum}privacy-level-enum" /&gt;
 *       &lt;attribute name="source-name" type="{http://www.cienciavitae.pt/ns/common}string-120-stype" /&gt;
 *       &lt;attribute ref="{http://www.cienciavitae.pt/ns/common}last-modified-date"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "record-ctype")
@XmlSeeAlso({
    Distinction.class,
    ExtendedRecordCtype.class,
    Employment.class,
    Degree.class,
    LanguageCompetency.class,
    DomainActivity.class,
    WebAddress.class,
    MailingAddress.class,
    PhoneNumber.class,
    Email.class,
    AuthorIdentifier.class
})
public class RecordCtype {

    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "privacy-level", required = true)
    protected PrivacyLevelEnum privacyLevel;
    @XmlAttribute(name = "source-name")
    protected String sourceName;
    @XmlAttribute(name = "last-modified-date", namespace = "http://www.cienciavitae.pt/ns/common")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDate;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the privacyLevel property.
     * 
     * @return
     *     possible object is
     *     {@link PrivacyLevelEnum }
     *     
     */
    public PrivacyLevelEnum getPrivacyLevel() {
        return privacyLevel;
    }

    /**
     * Sets the value of the privacyLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivacyLevelEnum }
     *     
     */
    public void setPrivacyLevel(PrivacyLevelEnum value) {
        this.privacyLevel = value;
    }

    /**
     * Gets the value of the sourceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * Sets the value of the sourceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceName(String value) {
        this.sourceName = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDate(XMLGregorianCalendar value) {
        this.lastModifiedDate = value;
    }

}
