//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for supervisor-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="supervisor-ctype"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="supervisor-name" type="{http://www.cienciavitae.pt/ns/common}string-120-stype"/&gt;
 *         &lt;element name="supervisor-role" type="{http://www.cienciavitae.pt/ns/common}supervisor-role-ctype"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="ciencia-id" type="{http://www.cienciavitae.pt/ns/common}string-14-stype" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "supervisor-ctype", propOrder = {
    "supervisorName",
    "supervisorRole"
})
public class SupervisorCtype {

    @XmlElement(name = "supervisor-name", required = true)
    protected String supervisorName;
    @XmlElement(name = "supervisor-role", required = true)
    protected SupervisorRoleCtype supervisorRole;
    @XmlAttribute(name = "ciencia-id")
    protected String cienciaId;

    /**
     * Gets the value of the supervisorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupervisorName() {
        return supervisorName;
    }

    /**
     * Sets the value of the supervisorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupervisorName(String value) {
        this.supervisorName = value;
    }

    /**
     * Gets the value of the supervisorRole property.
     * 
     * @return
     *     possible object is
     *     {@link SupervisorRoleCtype }
     *     
     */
    public SupervisorRoleCtype getSupervisorRole() {
        return supervisorRole;
    }

    /**
     * Sets the value of the supervisorRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupervisorRoleCtype }
     *     
     */
    public void setSupervisorRole(SupervisorRoleCtype value) {
        this.supervisorRole = value;
    }

    /**
     * Gets the value of the cienciaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCienciaId() {
        return cienciaId;
    }

    /**
     * Sets the value of the cienciaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCienciaId(String value) {
        this.cienciaId = value;
    }

}
