//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.funding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.DateCtype;
import pt.cienciavitae.ns.common.ExtendedRecordCtype;
import pt.cienciavitae.ns.common.InstitutionsCtype;
import pt.cienciavitae.ns.common.KeywordsCtype;
import pt.cienciavitae.ns.common.ResearchClassificationsCtype;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.cienciavitae.pt/ns/common}extended-record-ctype"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="funding-category" type="{http://www.cienciavitae.pt/ns/funding}funding-category-ctype"/&gt;
 *         &lt;element name="project-title" type="{http://www.cienciavitae.pt/ns/common}string-300-stype"/&gt;
 *         &lt;element name="project-description" type="{http://www.cienciavitae.pt/ns/common}string-4000-stype" minOccurs="0"/&gt;
 *         &lt;element name="start-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *         &lt;element name="end-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *         &lt;element name="start-date-participation" type="{http://www.cienciavitae.pt/ns/common}date-ctype"/&gt;
 *         &lt;element name="end-date-participation" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.cienciavitae.pt/ns/funding}status-ctype" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cienciavitae.pt/ns/common}funding-institutions" minOccurs="0"/&gt;
 *         &lt;element name="program-name" type="{http://www.cienciavitae.pt/ns/common}string-255-stype" minOccurs="0"/&gt;
 *         &lt;element name="year-awarded" type="{http://www.cienciavitae.pt/ns/common}year-stype" minOccurs="0"/&gt;
 *         &lt;element name="investigation-role" type="{http://www.cienciavitae.pt/ns/funding}investigation-role-ctype" minOccurs="0"/&gt;
 *         &lt;element name="investigation-role-description" type="{http://www.cienciavitae.pt/ns/funding}investigation-role-description-ctype" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cienciavitae.pt/ns/common}institutions" minOccurs="0"/&gt;
 *         &lt;group ref="{http://www.cienciavitae.pt/ns/funding}funding-group"/&gt;
 *         &lt;element name="funding-identifiers" type="{http://www.cienciavitae.pt/ns/funding}funding-identifiers-ctype" minOccurs="0"/&gt;
 *         &lt;element name="investigators" type="{http://www.cienciavitae.pt/ns/funding}investigators-ctype" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cienciavitae.pt/ns/common}research-classifications" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.cienciavitae.pt/ns/common}keywords" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fundingCategory",
    "projectTitle",
    "projectDescription",
    "startDate",
    "endDate",
    "startDateParticipation",
    "endDateParticipation",
    "status",
    "fundingInstitutions",
    "programName",
    "yearAwarded",
    "investigationRole",
    "investigationRoleDescription",
    "institutions",
    "totalAmount",
    "competitive",
    "fundingRenewable",
    "fundingIdentifiers",
    "investigators",
    "researchClassifications",
    "keywords"
})
@XmlRootElement(name = "funding")
public class Funding
    extends ExtendedRecordCtype
{

    @XmlElement(name = "funding-category", required = true)
    protected FundingCategoryCtype fundingCategory;
    @XmlElement(name = "project-title", required = true)
    protected String projectTitle;
    @XmlElement(name = "project-description")
    protected String projectDescription;
    @XmlElement(name = "start-date")
    protected DateCtype startDate;
    @XmlElement(name = "end-date")
    protected DateCtype endDate;
    @XmlElement(name = "start-date-participation", required = true)
    protected DateCtype startDateParticipation;
    @XmlElement(name = "end-date-participation")
    protected DateCtype endDateParticipation;
    protected StatusCtype status;
    @XmlElement(name = "funding-institutions", namespace = "http://www.cienciavitae.pt/ns/common")
    protected InstitutionsCtype fundingInstitutions;
    @XmlElement(name = "program-name")
    protected String programName;
    @XmlElement(name = "year-awarded")
    protected String yearAwarded;
    @XmlElement(name = "investigation-role")
    protected InvestigationRoleCtype investigationRole;
    @XmlElement(name = "investigation-role-description")
    protected InvestigationRoleDescriptionCtype investigationRoleDescription;
    @XmlElement(namespace = "http://www.cienciavitae.pt/ns/common")
    protected InstitutionsCtype institutions;
    @XmlElement(name = "total-amount")
    protected TotalAmountCtype totalAmount;
    protected Boolean competitive;
    @XmlElement(name = "funding-renewable")
    protected Boolean fundingRenewable;
    @XmlElement(name = "funding-identifiers")
    protected FundingIdentifiersCtype fundingIdentifiers;
    protected InvestigatorsCtype investigators;
    @XmlElement(name = "research-classifications", namespace = "http://www.cienciavitae.pt/ns/common")
    protected ResearchClassificationsCtype researchClassifications;
    @XmlElement(namespace = "http://www.cienciavitae.pt/ns/common")
    protected KeywordsCtype keywords;

    /**
     * Gets the value of the fundingCategory property.
     * 
     * @return
     *     possible object is
     *     {@link FundingCategoryCtype }
     *     
     */
    public FundingCategoryCtype getFundingCategory() {
        return fundingCategory;
    }

    /**
     * Sets the value of the fundingCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingCategoryCtype }
     *     
     */
    public void setFundingCategory(FundingCategoryCtype value) {
        this.fundingCategory = value;
    }

    /**
     * Gets the value of the projectTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectTitle() {
        return projectTitle;
    }

    /**
     * Sets the value of the projectTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectTitle(String value) {
        this.projectTitle = value;
    }

    /**
     * Gets the value of the projectDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectDescription() {
        return projectDescription;
    }

    /**
     * Sets the value of the projectDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectDescription(String value) {
        this.projectDescription = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setStartDate(DateCtype value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setEndDate(DateCtype value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the startDateParticipation property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getStartDateParticipation() {
        return startDateParticipation;
    }

    /**
     * Sets the value of the startDateParticipation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setStartDateParticipation(DateCtype value) {
        this.startDateParticipation = value;
    }

    /**
     * Gets the value of the endDateParticipation property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getEndDateParticipation() {
        return endDateParticipation;
    }

    /**
     * Sets the value of the endDateParticipation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setEndDateParticipation(DateCtype value) {
        this.endDateParticipation = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCtype }
     *     
     */
    public StatusCtype getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCtype }
     *     
     */
    public void setStatus(StatusCtype value) {
        this.status = value;
    }

    /**
     * Gets the value of the fundingInstitutions property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionsCtype }
     *     
     */
    public InstitutionsCtype getFundingInstitutions() {
        return fundingInstitutions;
    }

    /**
     * Sets the value of the fundingInstitutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionsCtype }
     *     
     */
    public void setFundingInstitutions(InstitutionsCtype value) {
        this.fundingInstitutions = value;
    }

    /**
     * Gets the value of the programName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramName() {
        return programName;
    }

    /**
     * Sets the value of the programName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramName(String value) {
        this.programName = value;
    }

    /**
     * Gets the value of the yearAwarded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYearAwarded() {
        return yearAwarded;
    }

    /**
     * Sets the value of the yearAwarded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYearAwarded(String value) {
        this.yearAwarded = value;
    }

    /**
     * Gets the value of the investigationRole property.
     * 
     * @return
     *     possible object is
     *     {@link InvestigationRoleCtype }
     *     
     */
    public InvestigationRoleCtype getInvestigationRole() {
        return investigationRole;
    }

    /**
     * Sets the value of the investigationRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestigationRoleCtype }
     *     
     */
    public void setInvestigationRole(InvestigationRoleCtype value) {
        this.investigationRole = value;
    }

    /**
     * Gets the value of the investigationRoleDescription property.
     * 
     * @return
     *     possible object is
     *     {@link InvestigationRoleDescriptionCtype }
     *     
     */
    public InvestigationRoleDescriptionCtype getInvestigationRoleDescription() {
        return investigationRoleDescription;
    }

    /**
     * Sets the value of the investigationRoleDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestigationRoleDescriptionCtype }
     *     
     */
    public void setInvestigationRoleDescription(InvestigationRoleDescriptionCtype value) {
        this.investigationRoleDescription = value;
    }

    /**
     * Gets the value of the institutions property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionsCtype }
     *     
     */
    public InstitutionsCtype getInstitutions() {
        return institutions;
    }

    /**
     * Sets the value of the institutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionsCtype }
     *     
     */
    public void setInstitutions(InstitutionsCtype value) {
        this.institutions = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link TotalAmountCtype }
     *     
     */
    public TotalAmountCtype getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalAmountCtype }
     *     
     */
    public void setTotalAmount(TotalAmountCtype value) {
        this.totalAmount = value;
    }

    /**
     * Gets the value of the competitive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCompetitive() {
        return competitive;
    }

    /**
     * Sets the value of the competitive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCompetitive(Boolean value) {
        this.competitive = value;
    }

    /**
     * Gets the value of the fundingRenewable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFundingRenewable() {
        return fundingRenewable;
    }

    /**
     * Sets the value of the fundingRenewable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFundingRenewable(Boolean value) {
        this.fundingRenewable = value;
    }

    /**
     * Gets the value of the fundingIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link FundingIdentifiersCtype }
     *     
     */
    public FundingIdentifiersCtype getFundingIdentifiers() {
        return fundingIdentifiers;
    }

    /**
     * Sets the value of the fundingIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link FundingIdentifiersCtype }
     *     
     */
    public void setFundingIdentifiers(FundingIdentifiersCtype value) {
        this.fundingIdentifiers = value;
    }

    /**
     * Gets the value of the investigators property.
     * 
     * @return
     *     possible object is
     *     {@link InvestigatorsCtype }
     *     
     */
    public InvestigatorsCtype getInvestigators() {
        return investigators;
    }

    /**
     * Sets the value of the investigators property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvestigatorsCtype }
     *     
     */
    public void setInvestigators(InvestigatorsCtype value) {
        this.investigators = value;
    }

    /**
     * Gets the value of the researchClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public ResearchClassificationsCtype getResearchClassifications() {
        return researchClassifications;
    }

    /**
     * Sets the value of the researchClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResearchClassificationsCtype }
     *     
     */
    public void setResearchClassifications(ResearchClassificationsCtype value) {
        this.researchClassifications = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordsCtype }
     *     
     */
    public KeywordsCtype getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordsCtype }
     *     
     */
    public void setKeywords(KeywordsCtype value) {
        this.keywords = value;
    }

}
