//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.funding;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for investigator-ctype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="investigator-ctype"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.cienciavitae.pt/ns/common&gt;string-120-stype"&gt;
 *       &lt;attribute name="ciencia-id" type="{http://www.cienciavitae.pt/ns/common}string-14-stype" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "investigator-ctype", propOrder = {
    "value"
})
public class InvestigatorCtype {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "ciencia-id")
    protected String cienciaId;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the cienciaId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCienciaId() {
        return cienciaId;
    }

    /**
     * Sets the value of the cienciaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCienciaId(String value) {
        this.cienciaId = value;
    }

}
