//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common_enum;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for employment-category-enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="employment-category-enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="T01"/&gt;
 *     &lt;enumeration value="T02"/&gt;
 *     &lt;enumeration value="T03"/&gt;
 *     &lt;enumeration value="T04"/&gt;
 *     &lt;enumeration value="T00"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "employment-category-enum", namespace = "http://www.cienciavitae.pt/ns/common-enum")
@XmlEnum
public enum EmploymentCategoryEnum {


    /**
     * PT: Ciência / EN: Science
     * 
     */
    @XmlEnumValue("T01")
    T_01("T01"),

    /**
     * PT: Docência no Ensino Superior / EN: Teaching in Higher Education
     * 
     */
    @XmlEnumValue("T02")
    T_02("T02"),

    /**
     * PT: Outras Carreiras / EN: Other Careers
     * 
     */
    @XmlEnumValue("T03")
    T_03("T03"),

    /**
     * PT: Cargos e Funções / EN: Positions / Appointments
     * 
     */
    @XmlEnumValue("T04")
    T_04("T04"),

    /**
     * PT: Outros / EN: Others
     * 
     */
    @XmlEnumValue("T00")
    T_00("T00");
    private final String value;

    EmploymentCategoryEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EmploymentCategoryEnum fromValue(String v) {
        for (EmploymentCategoryEnum c: EmploymentCategoryEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
