//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common_enum;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for institution-sector-enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="institution-sector-enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="S01"/&gt;
 *     &lt;enumeration value="S02"/&gt;
 *     &lt;enumeration value="S03"/&gt;
 *     &lt;enumeration value="S04"/&gt;
 *     &lt;enumeration value="S05"/&gt;
 *     &lt;enumeration value="S00"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "institution-sector-enum", namespace = "http://www.cienciavitae.pt/ns/common-enum")
@XmlEnum
public enum InstitutionSectorEnum {


    /**
     * PT: Ensino / EN: Academic
     * 
     */
    @XmlEnumValue("S01")
    S_01("S01"),

    /**
     * PT: Empresas / EN: Companies
     * 
     */
    @XmlEnumValue("S02")
    S_02("S02"),

    /**
     * PT: Saúde / EN: Health
     * 
     */
    @XmlEnumValue("S03")
    S_03("S03"),

    /**
     * PT: Instituições de I&D / EN: R&D Institutions
     * 
     */
    @XmlEnumValue("S04")
    S_04("S04"),

    /**
     * PT: Administração pública / EN: Government
     * 
     */
    @XmlEnumValue("S05")
    S_05("S05"),

    /**
     * PT: Outro / EN: Other
     * 
     */
    @XmlEnumValue("S00")
    S_00("S00");
    private final String value;

    InstitutionSectorEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InstitutionSectorEnum fromValue(String v) {
        for (InstitutionSectorEnum c: InstitutionSectorEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
