//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common_enum;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for language-level-enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="language-level-enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A1"/&gt;
 *     &lt;enumeration value="A2"/&gt;
 *     &lt;enumeration value="B1"/&gt;
 *     &lt;enumeration value="B2"/&gt;
 *     &lt;enumeration value="C1"/&gt;
 *     &lt;enumeration value="C2"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "language-level-enum", namespace = "http://www.cienciavitae.pt/ns/common-enum")
@XmlEnum
public enum LanguageLevelEnum {


    /**
     * PT: Utilizador elementar (A1) / EN: Beginner (A1)
     * 
     */
    @XmlEnumValue("A1")
    A_1("A1"),

    /**
     * PT: Utilizador elementar (A2) / EN: Elementary (A2)
     * 
     */
    @XmlEnumValue("A2")
    A_2("A2"),

    /**
     * PT: Utilizador independente (B1) / EN: Intermediate (B1)
     * 
     */
    @XmlEnumValue("B1")
    B_1("B1"),

    /**
     * PT: Utilizador independente (B2) / EN: Upper intermediate (B2)
     * 
     */
    @XmlEnumValue("B2")
    B_2("B2"),

    /**
     * PT: Utilizador proficiente (C1) / EN: Advanced (C1)
     * 
     */
    @XmlEnumValue("C1")
    C_1("C1"),

    /**
     * PT: Utilizador proficiente (C2) / EN: Proficiency (C2)
     * 
     */
    @XmlEnumValue("C2")
    C_2("C2");
    private final String value;

    LanguageLevelEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LanguageLevelEnum fromValue(String v) {
        for (LanguageLevelEnum c: LanguageLevelEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
