//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common_enum;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for output-publication-role-enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="output-publication-role-enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AT"/&gt;
 *     &lt;enumeration value="CA"/&gt;
 *     &lt;enumeration value="TD"/&gt;
 *     &lt;enumeration value="ED"/&gt;
 *     &lt;enumeration value="PS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "output-publication-role-enum", namespace = "http://www.cienciavitae.pt/ns/common-enum")
@XmlEnum
public enum OutputPublicationRoleEnum {


    /**
     * PT: Autor / EN: Author
     * 
     */
    AT,

    /**
     * PT: Co-autor / EN: Coauthor
     * 
     */
    CA,

    /**
     * PT: Tradutor / EN: Translator
     * 
     */
    TD,

    /**
     * PT: Editor / EN: Editor
     * 
     */
    ED,

    /**
     * PT: Pessoal de suporte / EN: Assistant staff
     * 
     */
    PS;

    public String value() {
        return name();
    }

    public static OutputPublicationRoleEnum fromValue(String v) {
        return valueOf(v);
    }

}
