//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common_enum;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for output-type-enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="output-type-enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="P101"/&gt;
 *     &lt;enumeration value="P102"/&gt;
 *     &lt;enumeration value="P103"/&gt;
 *     &lt;enumeration value="P104"/&gt;
 *     &lt;enumeration value="P105"/&gt;
 *     &lt;enumeration value="P106"/&gt;
 *     &lt;enumeration value="P107"/&gt;
 *     &lt;enumeration value="P108"/&gt;
 *     &lt;enumeration value="P110"/&gt;
 *     &lt;enumeration value="P111"/&gt;
 *     &lt;enumeration value="P112"/&gt;
 *     &lt;enumeration value="P113"/&gt;
 *     &lt;enumeration value="P114"/&gt;
 *     &lt;enumeration value="P115"/&gt;
 *     &lt;enumeration value="P116"/&gt;
 *     &lt;enumeration value="P118"/&gt;
 *     &lt;enumeration value="P119"/&gt;
 *     &lt;enumeration value="P120"/&gt;
 *     &lt;enumeration value="P121"/&gt;
 *     &lt;enumeration value="P122"/&gt;
 *     &lt;enumeration value="P123"/&gt;
 *     &lt;enumeration value="P124"/&gt;
 *     &lt;enumeration value="P125"/&gt;
 *     &lt;enumeration value="P126"/&gt;
 *     &lt;enumeration value="P301"/&gt;
 *     &lt;enumeration value="P302"/&gt;
 *     &lt;enumeration value="P304"/&gt;
 *     &lt;enumeration value="P305"/&gt;
 *     &lt;enumeration value="P306"/&gt;
 *     &lt;enumeration value="P307"/&gt;
 *     &lt;enumeration value="P308"/&gt;
 *     &lt;enumeration value="P309"/&gt;
 *     &lt;enumeration value="P310"/&gt;
 *     &lt;enumeration value="P311"/&gt;
 *     &lt;enumeration value="P312"/&gt;
 *     &lt;enumeration value="P313"/&gt;
 *     &lt;enumeration value="P314"/&gt;
 *     &lt;enumeration value="P315"/&gt;
 *     &lt;enumeration value="P316"/&gt;
 *     &lt;enumeration value="P317"/&gt;
 *     &lt;enumeration value="P401"/&gt;
 *     &lt;enumeration value="P402"/&gt;
 *     &lt;enumeration value="P403"/&gt;
 *     &lt;enumeration value="P404"/&gt;
 *     &lt;enumeration value="P405"/&gt;
 *     &lt;enumeration value="P501"/&gt;
 *     &lt;enumeration value="P502"/&gt;
 *     &lt;enumeration value="P503"/&gt;
 *     &lt;enumeration value="P504"/&gt;
 *     &lt;enumeration value="P505"/&gt;
 *     &lt;enumeration value="P506"/&gt;
 *     &lt;enumeration value="P507"/&gt;
 *     &lt;enumeration value="P508"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "output-type-enum", namespace = "http://www.cienciavitae.pt/ns/common-enum")
@XmlEnum
public enum OutputTypeEnum {


    /**
     * PT: Artigo em revista / EN: Journal article
     * 
     */
    @XmlEnumValue("P101")
    P_101("P101"),

    /**
     * PT: Edição de número de revista / EN: Journal issue
     * 
     */
    @XmlEnumValue("P102")
    P_102("P102"),

    /**
     * PT: Livro / EN: Book
     * 
     */
    @XmlEnumValue("P103")
    P_103("P103"),

    /**
     * PT: Edição de livro / EN: Edited book
     * 
     */
    @XmlEnumValue("P104")
    P_104("P104"),

    /**
     * PT: Capítulo de livro / EN: Book chapter
     * 
     */
    @XmlEnumValue("P105")
    P_105("P105"),

    /**
     * PT: Revisão de livro / EN: Book review
     * 
     */
    @XmlEnumValue("P106")
    P_106("P106"),

    /**
     * PT: Tradução / EN: Translation
     * 
     */
    @XmlEnumValue("P107")
    P_107("P107"),

    /**
     * PT: Tese / Dissertação / EN: Thesis / Dissertation
     * 
     */
    @XmlEnumValue("P108")
    P_108("P108"),

    /**
     * PT: Artigo em jornal / EN: Newspaper article
     * 
     */
    @XmlEnumValue("P110")
    P_110("P110"),

    /**
     * PT: Artigo em boletim informativo / EN: Newsletter article
     * 
     */
    @XmlEnumValue("P111")
    P_111("P111"),

    /**
     * PT: Entrada de enciclopédia / EN: Encyclopedia Entry
     * 
     */
    @XmlEnumValue("P112")
    P_112("P112"),

    /**
     * PT: Artigo em revista (magazine) / EN: Magazine article
     * 
     */
    @XmlEnumValue("P113")
    P_113("P113"),

    /**
     * PT: Entrada de dicionário / EN: Dictionary entry
     * 
     */
    @XmlEnumValue("P114")
    P_114("P114"),

    /**
     * PT: Relatório / EN: Report
     * 
     */
    @XmlEnumValue("P115")
    P_115("P115"),

    /**
     * PT: Documento de trabalho / EN: Working paper
     * 
     */
    @XmlEnumValue("P116")
    P_116("P116"),

    /**
     * PT: Manual / EN: Manual
     * 
     */
    @XmlEnumValue("P118")
    P_118("P118"),

    /**
     * PT: Recurso online / EN: Online resource
     * 
     */
    @XmlEnumValue("P119")
    P_119("P119"),

    /**
     * PT: Enunciado de teste / EN: Test
     * 
     */
    @XmlEnumValue("P120")
    P_120("P120"),

    /**
     * PT: Website / EN: Website
     * 
     */
    @XmlEnumValue("P121")
    P_121("P121"),

    /**
     * PT: Artigo em conferência / EN: Conference paper
     * 
     */
    @XmlEnumValue("P122")
    P_122("P122"),

    /**
     * PT: Resumo em conferência / EN: Conference abstract
     * 
     */
    @XmlEnumValue("P123")
    P_123("P123"),

    /**
     * PT: Poster em conferência / EN: Conference poster
     * 
     */
    @XmlEnumValue("P124")
    P_124("P124"),

    /**
     * PT: Catálogo de exposição / EN: Exhibition catalog
     * 
     */
    @XmlEnumValue("P125")
    P_125("P125"),

    /**
     * PT: Prefácio / Posfácio / EN: Preface / Postscript
     * 
     */
    @XmlEnumValue("P126")
    P_126("P126"),

    /**
     * PT: Exposição artística / EN: Artistic exhibition
     * 
     */
    @XmlEnumValue("P301")
    P_301("P301"),

    /**
     * PT: Gravação áudio / EN: Audio recording
     * 
     */
    @XmlEnumValue("P302")
    P_302("P302"),

    /**
     * PT: Composição musical / EN: Musical composition
     * 
     */
    @XmlEnumValue("P304")
    P_304("P304"),

    /**
     * PT: Interpretação musical / EN: Musical performance
     * 
     */
    @XmlEnumValue("P305")
    P_305("P305"),

    /**
     * PT: Programa de rádio / tv / EN: Program / Show
     * 
     */
    @XmlEnumValue("P306")
    P_306("P306"),

    /**
     * PT: Guião / EN: Script
     * 
     */
    @XmlEnumValue("P307")
    P_307("P307"),

    /**
     * PT: Conto de ficção / EN: Short fiction
     * 
     */
    @XmlEnumValue("P308")
    P_308("P308"),

    /**
     * PT: Obra teatral / EN: Theatre play
     * 
     */
    @XmlEnumValue("P309")
    P_309("P309"),

    /**
     * PT: Gravação vídeo / EN: Video recording
     * 
     */
    @XmlEnumValue("P310")
    P_310("P310"),

    /**
     * PT: Arte visual / EN: Visual artwork
     * 
     */
    @XmlEnumValue("P311")
    P_311("P311"),

    /**
     * PT: Projeto de som / EN: Sound design
     * 
     */
    @XmlEnumValue("P312")
    P_312("P312"),

    /**
     * PT: Cenografia / EN: Set design
     * 
     */
    @XmlEnumValue("P313")
    P_313("P313"),

    /**
     * PT: Projeto de luz / EN: Light design
     * 
     */
    @XmlEnumValue("P314")
    P_314("P314"),

    /**
     * PT: Coreografia / EN: Choreography
     * 
     */
    @XmlEnumValue("P315")
    P_315("P315"),

    /**
     * PT: Exposição de curadoria / museu / EN: Curatorial / Museum exhibition
     * 
     */
    @XmlEnumValue("P316")
    P_316("P316"),

    /**
     * PT: Interpretação artística / EN: Artistic Performance
     * 
     */
    @XmlEnumValue("P317")
    P_317("P317"),

    /**
     * PT: Patente / EN: Patent
     * 
     */
    @XmlEnumValue("P401")
    P_401("P401"),

    /**
     * PT: Licenciamento / EN: Licensing patent rights
     * 
     */
    @XmlEnumValue("P402")
    P_402("P402"),

    /**
     * PT: Pedido provisório de patente / EN: Provisional application for patent
     * 
     */
    @XmlEnumValue("P403")
    P_403("P403"),

    /**
     * PT: Registo de direitos de autor / EN: Copyright registration
     * 
     */
    @XmlEnumValue("P404")
    P_404("P404"),

    /**
     * PT: Marca registada / EN: Trademark
     * 
     */
    @XmlEnumValue("P405")
    P_405("P405"),

    /**
     * PT: Norma ou política / EN: Standard or policy
     * 
     */
    @XmlEnumValue("P501")
    P_501("P501"),

    /**
     * PT: Invenção / EN: Invention
     * 
     */
    @XmlEnumValue("P502")
    P_502("P502"),

    /**
     * PT: Conjunto de dados / EN: Dataset
     * 
     */
    @XmlEnumValue("P503")
    P_503("P503"),

    /**
     * PT: Processo judicial / EN: Legal proceeding
     * 
     */
    @XmlEnumValue("P504")
    P_504("P504"),

    /**
     * PT: Técnica de investigação / EN: Research technique
     * 
     */
    @XmlEnumValue("P505")
    P_505("P505"),

    /**
     * PT: Empresa spin-off / EN: Spin-off company
     * 
     */
    @XmlEnumValue("P506")
    P_506("P506"),

    /**
     * PT: Norma técnica / EN: Technical standard
     * 
     */
    @XmlEnumValue("P507")
    P_507("P507"),

    /**
     * PT: Outra produção / EN: Other output
     * 
     */
    @XmlEnumValue("P508")
    P_508("P508");
    private final String value;

    OutputTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OutputTypeEnum fromValue(String v) {
        for (OutputTypeEnum c: OutputTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
