//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common_enum;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for service-category-enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="service-category-enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="S101"/&gt;
 *     &lt;enumeration value="S102"/&gt;
 *     &lt;enumeration value="S103"/&gt;
 *     &lt;enumeration value="S104"/&gt;
 *     &lt;enumeration value="S105"/&gt;
 *     &lt;enumeration value="S106"/&gt;
 *     &lt;enumeration value="S107"/&gt;
 *     &lt;enumeration value="S108"/&gt;
 *     &lt;enumeration value="S109"/&gt;
 *     &lt;enumeration value="S110"/&gt;
 *     &lt;enumeration value="S111"/&gt;
 *     &lt;enumeration value="S112"/&gt;
 *     &lt;enumeration value="S201"/&gt;
 *     &lt;enumeration value="S202"/&gt;
 *     &lt;enumeration value="S203"/&gt;
 *     &lt;enumeration value="S204"/&gt;
 *     &lt;enumeration value="S205"/&gt;
 *     &lt;enumeration value="S206"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "service-category-enum", namespace = "http://www.cienciavitae.pt/ns/common-enum")
@XmlEnum
public enum ServiceCategoryEnum {


    /**
     * PT: Consultoria / Parecer / EN: Consulting
     * 
     */
    @XmlEnumValue("S101")
    S_101("S101"),

    /**
     * PT: Processo legal / EN: Legal proceeding
     * 
     */
    @XmlEnumValue("S102")
    S_102("S102"),

    /**
     * PT: Arbitragem científica em revista / EN: Journal scientific committee
     * 
     */
    @XmlEnumValue("S103")
    S_103("S103"),

    /**
     * PT: Arbitragem científica em conferência / EN: Conference scientific committee
     * 
     */
    @XmlEnumValue("S104")
    S_104("S104"),

    /**
     * PT: Júri de grau académico / EN: Jury of academic degree
     * 
     */
    @XmlEnumValue("S105")
    S_105("S105"),

    /**
     * PT: Comissão de avaliação / EN: Evaluation committee
     * 
     */
    @XmlEnumValue("S106")
    S_106("S106"),

    /**
     * PT: Tutoria / EN: Mentoring / Tutoring
     * 
     */
    @XmlEnumValue("S107")
    S_107("S107"),

    /**
     * PT: Entrevista / Programa (rádio / tv) / EN: Interview (tv / radio show)
     * 
     */
    @XmlEnumValue("S108")
    S_108("S108"),

    /**
     * PT: Entrevista (jornal / revista) / EN: Interview (newspaper / magazine)
     * 
     */
    @XmlEnumValue("S109")
    S_109("S109"),

    /**
     * PT: Orientação / EN: Supervision
     * 
     */
    @XmlEnumValue("S110")
    S_110("S110"),

    /**
     * PT: Outro júri / avaliação / EN: Other jury / evaluation
     * 
     */
    @XmlEnumValue("S111")
    S_111("S111"),

    /**
     * PT: Expedição científica / EN: Scientific expedition
     * 
     */
    @XmlEnumValue("S112")
    S_112("S112"),

    /**
     * PT: Organização de evento / EN: Event organisation
     * 
     */
    @XmlEnumValue("S201")
    S_201("S201"),

    /**
     * PT: Participação em evento / EN: Event participation
     * 
     */
    @XmlEnumValue("S202")
    S_202("S202"),

    /**
     * PT: Membro de associação / EN: Association member
     * 
     */
    @XmlEnumValue("S203")
    S_203("S203"),

    /**
     * PT: Curso / Disciplina leccionado / EN: Course / Discipline taught
     * 
     */
    @XmlEnumValue("S204")
    S_204("S204"),

    /**
     * PT: Apresentação oral de trabalho / EN: Oral presentation
     * 
     */
    @XmlEnumValue("S205")
    S_205("S205"),

    /**
     * PT: Membro de comissão / EN: Committee member
     * 
     */
    @XmlEnumValue("S206")
    S_206("S206");
    private final String value;

    ServiceCategoryEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceCategoryEnum fromValue(String v) {
        for (ServiceCategoryEnum c: ServiceCategoryEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
