//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common_enum;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for service-degree-type-enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="service-degree-type-enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CA"/&gt;
 *     &lt;enumeration value="D"/&gt;
 *     &lt;enumeration value="IC"/&gt;
 *     &lt;enumeration value="LB"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *     &lt;enumeration value="O"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "service-degree-type-enum", namespace = "http://www.cienciavitae.pt/ns/common-enum")
@XmlEnum
public enum ServiceDegreeTypeEnum {


    /**
     * PT: Curso de aperfeiçoamento / especialização / EN: Specialization course
     * 
     */
    CA,

    /**
     * PT: Doutoramento / EN: PhD
     * 
     */
    D,

    /**
     * PT: Iniciação científica / EN: Scientific initiation
     * 
     */
    IC,

    /**
     * PT: Licenciatura / Bacharelato / EN: Degree
     * 
     */
    LB,

    /**
     * PT: Mestrado / EN: Master
     * 
     */
    M,

    /**
     * PT: Outra / EN: Other
     * 
     */
    O;

    public String value() {
        return name();
    }

    public static ServiceDegreeTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
