//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.common_enum;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for service-administrative-role-enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="service-administrative-role-enum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="CO"/&gt;
 *     &lt;enumeration value="MCC"/&gt;
 *     &lt;enumeration value="MCO"/&gt;
 *     &lt;enumeration value="OTR"/&gt;
 *     &lt;enumeration value="PCO"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "service-administrative-role-enum", namespace = "http://www.cienciavitae.pt/ns/common-enum")
@XmlEnum
public enum ServiceAdministrativeRoleEnum {


    /**
     * PT: Coorganizador / EN: Co-organisor
     * 
     */
    CO,

    /**
     * PT: Membro da Comissão Científica / EN: Member of the Scientific Committee
     * 
     */
    MCC,

    /**
     * PT: Membro da Comissão Organizadora / EN: Member of the Organising Committee
     * 
     */
    MCO,

    /**
     * PT: Outra / EN: Other
     * 
     */
    OTR,

    /**
     * PT: Presidente da Comissão Organizadora / EN: President of the Organizing Committee
     * 
     */
    PCO;

    public String value() {
        return name();
    }

    public static ServiceAdministrativeRoleEnum fromValue(String v) {
        return valueOf(v);
    }

}
