//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.employment;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import pt.cienciavitae.ns.common.DateCtype;
import pt.cienciavitae.ns.common.InstitutionCtype;
import pt.cienciavitae.ns.common.InstitutionsCtype;
import pt.cienciavitae.ns.common.RecordCtype;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.cienciavitae.pt/ns/common}record-ctype"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="employment-category" type="{http://www.cienciavitae.pt/ns/employment}employment-category-ctype"/&gt;
 *         &lt;element ref="{http://www.cienciavitae.pt/ns/common}institution"/&gt;
 *         &lt;element name="position-type" type="{http://www.cienciavitae.pt/ns/employment}employment-position-type-ctype" minOccurs="0"/&gt;
 *         &lt;element name="position-title" type="{http://www.cienciavitae.pt/ns/employment}employment-position-title-ctype" minOccurs="0"/&gt;
 *         &lt;element name="position-title-group" type="{http://www.cienciavitae.pt/ns/employment}employment-position-title-group-ctype" minOccurs="0"/&gt;
 *         &lt;element name="host-institutions" type="{http://www.cienciavitae.pt/ns/common}institutions-ctype" minOccurs="0"/&gt;
 *         &lt;element name="start-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype"/&gt;
 *         &lt;element name="end-date" type="{http://www.cienciavitae.pt/ns/common}date-ctype" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "employmentCategory",
    "institution",
    "positionType",
    "positionTitle",
    "positionTitleGroup",
    "hostInstitutions",
    "startDate",
    "endDate"
})
@XmlRootElement(name = "employment")
public class Employment
    extends RecordCtype
{

    @XmlElement(name = "employment-category", required = true)
    protected EmploymentCategoryCtype employmentCategory;
    @XmlElement(namespace = "http://www.cienciavitae.pt/ns/common", required = true)
    protected InstitutionCtype institution;
    @XmlElement(name = "position-type")
    protected EmploymentPositionTypeCtype positionType;
    @XmlElement(name = "position-title")
    protected EmploymentPositionTitleCtype positionTitle;
    @XmlElement(name = "position-title-group")
    protected EmploymentPositionTitleGroupCtype positionTitleGroup;
    @XmlElement(name = "host-institutions")
    protected InstitutionsCtype hostInstitutions;
    @XmlElement(name = "start-date", required = true)
    protected DateCtype startDate;
    @XmlElement(name = "end-date")
    protected DateCtype endDate;

    /**
     * Gets the value of the employmentCategory property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentCategoryCtype }
     *     
     */
    public EmploymentCategoryCtype getEmploymentCategory() {
        return employmentCategory;
    }

    /**
     * Sets the value of the employmentCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentCategoryCtype }
     *     
     */
    public void setEmploymentCategory(EmploymentCategoryCtype value) {
        this.employmentCategory = value;
    }

    /**
     * Gets the value of the institution property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionCtype }
     *     
     */
    public InstitutionCtype getInstitution() {
        return institution;
    }

    /**
     * Sets the value of the institution property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionCtype }
     *     
     */
    public void setInstitution(InstitutionCtype value) {
        this.institution = value;
    }

    /**
     * Gets the value of the positionType property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentPositionTypeCtype }
     *     
     */
    public EmploymentPositionTypeCtype getPositionType() {
        return positionType;
    }

    /**
     * Sets the value of the positionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentPositionTypeCtype }
     *     
     */
    public void setPositionType(EmploymentPositionTypeCtype value) {
        this.positionType = value;
    }

    /**
     * Gets the value of the positionTitle property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentPositionTitleCtype }
     *     
     */
    public EmploymentPositionTitleCtype getPositionTitle() {
        return positionTitle;
    }

    /**
     * Sets the value of the positionTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentPositionTitleCtype }
     *     
     */
    public void setPositionTitle(EmploymentPositionTitleCtype value) {
        this.positionTitle = value;
    }

    /**
     * Gets the value of the positionTitleGroup property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentPositionTitleGroupCtype }
     *     
     */
    public EmploymentPositionTitleGroupCtype getPositionTitleGroup() {
        return positionTitleGroup;
    }

    /**
     * Sets the value of the positionTitleGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentPositionTitleGroupCtype }
     *     
     */
    public void setPositionTitleGroup(EmploymentPositionTitleGroupCtype value) {
        this.positionTitleGroup = value;
    }

    /**
     * Gets the value of the hostInstitutions property.
     * 
     * @return
     *     possible object is
     *     {@link InstitutionsCtype }
     *     
     */
    public InstitutionsCtype getHostInstitutions() {
        return hostInstitutions;
    }

    /**
     * Sets the value of the hostInstitutions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstitutionsCtype }
     *     
     */
    public void setHostInstitutions(InstitutionsCtype value) {
        this.hostInstitutions = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setStartDate(DateCtype value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateCtype }
     *     
     */
    public DateCtype getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateCtype }
     *     
     */
    public void setEndDate(DateCtype value) {
        this.endDate = value;
    }

}
