//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.07 at 12:49:04 PM UTC 
//


package pt.cienciavitae.ns.employment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pt.cienciavitae.ns.employment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pt.cienciavitae.ns.employment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Employments }
     * 
     */
    public Employments createEmployments() {
        return new Employments();
    }

    /**
     * Create an instance of {@link Employment }
     * 
     */
    public Employment createEmployment() {
        return new Employment();
    }

    /**
     * Create an instance of {@link EmploymentCategoryCtype }
     * 
     */
    public EmploymentCategoryCtype createEmploymentCategoryCtype() {
        return new EmploymentCategoryCtype();
    }

    /**
     * Create an instance of {@link EmploymentPositionTypeCtype }
     * 
     */
    public EmploymentPositionTypeCtype createEmploymentPositionTypeCtype() {
        return new EmploymentPositionTypeCtype();
    }

    /**
     * Create an instance of {@link EmploymentPositionTitleCtype }
     * 
     */
    public EmploymentPositionTitleCtype createEmploymentPositionTitleCtype() {
        return new EmploymentPositionTitleCtype();
    }

    /**
     * Create an instance of {@link EmploymentPositionTitleGroupCtype }
     * 
     */
    public EmploymentPositionTitleGroupCtype createEmploymentPositionTitleGroupCtype() {
        return new EmploymentPositionTitleGroupCtype();
    }

}
